force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Closing_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closing_Reason__c</fullName>
    <label>Closing Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>לא ניתן ליצור קשר</fullName>
            </value>
            <value>
                <fullName>המעסיק חזר בו מפנייתו</fullName>
            </value>
            <value>
                <fullName>לא נמצאה תוכנית מתאימה</fullName>
            </value>
            <value>
                <fullName>בקשה כפולה</fullName>
            </value>
            <value>
                <fullName>לא רלוונטי</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול בתוכנית</fullName>
                <label>מיפוי בוצע בהצלחה</label>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
                <isActive>false</isActive>
                <label>הועבר לטיפול המפעיל</label>
            </value>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
                <isActive>false</isActive>
                <label>הועבר למילוי טפסים</label>
            </value>
            <value>
                <fullName>לא ניתנה המלצה</fullName>
                <isActive>false</isActive>
                <label>לא ניתנה המלצה</label>
            </value>
            <value>
                <fullName>נתונים שגויים</fullName>
                <isActive>false</isActive>
                <label>נתונים שגויים</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DynamicPickListFectcher_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-02-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class DynamicPickListFectcher_Test {
    @isTest
    static void requestTest(){    
        Test.startTest();
        DynamicPickListFectcher.getPicklistOptions('Request__c', 'Closing_Reason__c');
        Test.stopTest();
    }
}