force-app/main/default/objects/Holland_questionnaire__c/Holland_questionnaire__c.object-meta.xml
<CustomObject>
    <label>שאלון הולנד</label>
    <nameField>
        <displayFormat>Q-{0000000}</displayFormat>
        <label>קוד שאלון</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>שאלוני הולנד</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holland_questionnaire__c/fields/A1__c.field-meta.xml
<CustomField>
    <fullName>A1__c</fullName>
    <label>1. להרכיב ארונות מטבח - קוד</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holland_questionnaire__c/fields/A60__c.field-meta.xml
<CustomField>
    <fullName>A60__c</fullName>
    <label>60.למיין ולחלק דואר של חברה/ארגון - קוד</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holland_questionnaire__c/fields/QuestionaireEducation__c.field-meta.xml
<CustomField>
    <fullName>QuestionaireEducation__c</fullName>
    <label>רמת השכלה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>ללא תעודת בגרות</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>תעודת בגרות</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>על תיכונית</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>תואר אקדמי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holland_questionnaire__c/fields/QuestionedAgeGroup__c.field-meta.xml
<CustomField>
    <fullName>QuestionedAgeGroup__c</fullName>
    <label>גיל</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>עד 25</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>26-40</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>41-55</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>מעל 55</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holland_questionnaire__c/fields/QuestionedGender__c.field-meta.xml
<CustomField>
    <fullName>QuestionedGender__c</fullName>
    <label>מין</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>זכר</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>נקבה</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HollandLog__c/HollandLog__c.object-meta.xml
<CustomObject>
    <description>Saves the Row Data + LOG of JSON Holland questionnaire from Rest API incoming POST REQUEST</description>
    <label>HollandLog</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>HollandLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HollandLog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HollandLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Contains the Error message from the DML Operations that invoked the creation of this Record</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HollandLog__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <description>JSON Data input from the API Client</description>
    <label>JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Occupation__c/Occupation__c.object-meta.xml
<CustomObject>
    <label>עיסוק</label>
    <nameField>
        <label>שם עיסוק לשון זכר</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>עיסוקים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Occupation__c/fields/OccupationMatrixId__c.field-meta.xml
<CustomField>
    <fullName>OccupationMatrixId__c</fullName>
    <externalId>true</externalId>
    <label>קוד MATRIX</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Occupation_recommendation__c/Occupation_recommendation__c.object-meta.xml
<CustomObject>
    <label>המלצת עיסוקים</label>
    <nameField>
        <label>מס&apos; המלצת עיסוקים</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>המלצות עיסוקים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Occupation_recommendation__c/fields/Holland_questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Holland_questionnaire__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>שאלון הולנד</label>
    <referenceTo>Holland_questionnaire__c</referenceTo>
    <relationshipLabel>המלצות עיסוקים</relationshipLabel>
    <relationshipName>Holland_questionnaire</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Occupation_recommendation__c/fields/ProfessionalFitDescription__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalFitDescription__c</fullName>
    <label>מידת התאמה לעיסוק</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Best</fullName>
            </value>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Great</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Occupation_recommendation__c/fields/ProfessionId__c.field-meta.xml
<CustomField>
    <fullName>ProfessionId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>עיסוק</label>
    <referenceTo>Occupation__c</referenceTo>
    <relationshipLabel>המלצות עיסוקים</relationshipLabel>
    <relationshipName>occupation_recommendation</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HollandHelper.cls
public without sharing class HollandHelper {
    
    public class ParsingException extends Exception {}
    
    public HollandHelper() {
        
    }
    
    
    public static void buildHolland(List<Holland> hollandInputDataList, String jsonString){
        System.debug('IN buildHolland()');
        List<Holland_questionnaire__c> hollandQuestionnairsToInsert = new List<Holland_questionnaire__c>();
        List<Occupation_recommendation__c> OccupationRecommendationToInsert = new List<Occupation_recommendation__c>();
        
        Savepoint savePoint = Database.setSavepoint(); /* RollBack insertion of records as the Apex Transaction will not roll back due to the try/catch block*/
        
        try {
            for (Integer i = 0; i < hollandInputDataList.size(); i++) {
                hollandQuestionnairsToInsert.add(buildResultObject(hollandInputDataList[i])); /* add and Procces each Holland input to create the final Holland_questionnaire__c */
            }
            insert hollandQuestionnairsToInsert; 
            
            List<Occupation_recommendation__c> occReccListToInsert = new List<Occupation_recommendation__c>();
            for (Integer i = 0; i < hollandQuestionnairsToInsert.size(); i++) { /* Proccess the Occupation_recommendations for each Holland_questionnaire__c */
                List<Occupation_recommendation__c> reccomendationsPerHolland = assignOccupationRecommendations(hollandQuestionnairsToInsert[i], hollandInputDataList[i]); /*  List of reccommendation per Holland_questionnaire__c */
                occReccListToInsert.addAll(reccomendationsPerHolland);
            }
            insert occReccListToInsert;
            
        } catch (Exception ex) {
            System.debug('IN HollandHelper: Error while building Holland. Message: ' + ex.getMessage());
            System.debug('IN HollandHelper: Creating Log in HollandLog__c ...');
            Database.rollback(savepoint); 
            createErrorLog(jsonString, ex);
            return;
        }      
        
    }
    
    
    private static Holland_questionnaire__c buildResultObject(Holland hollanData){
        Holland_questionnaire__c hollandQuestionnaire = new Holland_questionnaire__c();
        hollandQuestionnaire.QuestionedGender__c = hollanData.gender == 0 ? null : String.valueOf(hollanData.gender);
        hollandQuestionnaire.QuestionedAgeGroup__c = hollanData.age == 0 ? null : String.valueOf(hollanData.age);
        hollandQuestionnaire.QuestionaireEducation__c = hollanData.education == 0 ? null : String.valueOf(hollanData.education);
        
        hollandQuestionnaire = assignAnswers(hollandQuestionnaire, hollanData); /* Parse the 60 Chars String Answers and assign for the matching fields in Holland_questionnaire__c */
        hollandQuestionnaire = assignProfileScore(hollandQuestionnaire, hollanData);
        return hollandQuestionnaire;
    } 
    
    
    private static Holland_questionnaire__c assignAnswers(Holland_questionnaire__c hollandQuestionnaire, Holland hollandData){
        String answers = hollandData.answers;
        if (answers.length() != 60) {
            throw new ParsingException(Label.Did_not_received_full_answers_data);
        }
        
        
        Map<String, Schema.SObjectField> hollandQuestionnaireFields = Schema.SObjectType.Holland_questionnaire__c.fields.getMap();
        List<String> answersCodeCharArray = answers.split(''); /* String -> List of 60 Chars. Each char is a code to an answer  -> */
        
        /* Assigns each AnswerCode to the appropriate field (Fields names for answers are "A1__c" to "A60__c" ) */
        for (Integer indexOfCodeAnswer = 0; indexOfCodeAnswer < answersCodeCharArray.size(); indexOfCodeAnswer++) {
            hollandQuestionnaire.put('A' + (indexOfCodeAnswer+1) + '__c', answersCodeCharArray[indexOfCodeAnswer]);
        }
        
        
        return hollandQuestionnaire;
        
        
    } 
    
    private static Holland_questionnaire__c assignProfileScore(Holland_questionnaire__c hollandQuestionnaire, Holland hollandData){
        Map<String, Integer> profileScoreMap = new Map<String, Integer>();
        final List<String> AVAILIBLE_AREA_VALUES = new List<String>{'realistic','investigative','artistic','social','enterprising','conventional'};
        for (Holland.Profile_score profileScore : hollandData.profile_score) { /* Iterating on user input */
            String profileScoreArea = profileScore.area.replaceAll( '\\s+', '').toLowerCase(); /* Ignore white space and Letter Case in JSON */
            if (!AVAILIBLE_AREA_VALUES.contains(profileScoreArea)) {
                throw new ParsingException(String.Format(Label.No_matching_area_field_for_the_user_input, new List<String>{profileScore.area}));
                
            }
            if (profileScore.score == null) {
                String message = Label.No_score_value_for_Area_Field;
                throw new ParsingException(String.format(message, new List<String>{profileScore.area}));
            }
            profileScoreMap.put(profileScoreArea, profileScore.score);
        }
        if (profileScoreMap.size() != AVAILIBLE_AREA_VALUES.size()) {
            throw new ParsingException(String.Format(Label.expecting_for_X_fields_areas_from_input, new List<String>{ String.valueOf(AVAILIBLE_AREA_VALUES.size())}));
            
        }
        else {
            for (String area : AVAILIBLE_AREA_VALUES) {
                hollandQuestionnaire.put(area + 'ProfileScore__c', profileScoreMap.get(area));
            }
            return hollandQuestionnaire;
        }
        
    } 
    
    /* Iterates on Jsons Occupoations reccomendations and create Occupations <-> Holland Junctions object records for each one */
    private static List<Occupation_recommendation__c> assignOccupationRecommendations(Holland_questionnaire__c hollandQuestionnaire, Holland hollandData){
        List<Occupation_recommendation__c> occupationRecList = new List<Occupation_recommendation__c>();
        
        if (hollandData.occupations.size() == 0) {
            throw new ParsingException('occupations List must not be empty');
        }
        for (Holland.Occupations occupationFromInput : hollandData.occupations) {
            Occupation_recommendation__c occupationReccomendation = new Occupation_recommendation__c();
            occupationReccomendation.ProfessionalFitDescription__c = occupationFromInput.fit;
            occupationReccomendation.Holland_questionnaire__c = hollandQuestionnaire.Id;
            occupationReccomendation.ProfessionId__r = new Occupation__c(OccupationMatrixId__c = String.valueOf(occupationFromInput.code_occupation)); //TDOO: Change in SF UI External ID Code to be Number instead of String
            occupationRecList.add(occupationReccomendation);
        }
        
        return occupationRecList;
    } 
    
    
    
    /* Log errors if can't manage to build "Holland_questionnaire__c" or related records */
    private static void createErrorLog(String jsonStringFromClient, Exception ex){
        HollandLog__c hollandLog = new HollandLog__c();
        hollandLog.JSON__c = jsonStringFromClient;
        hollandLog.ErrorMessage__c = ex.getMessage();
        insert hollandLog;
    } 
}