force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>מזהה קורס</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>העיר בה מוסד ההכשרה מקיים את הקורס</inlineHelpText>
    <label>עיר</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CityName__c.field-meta.xml
<CustomField>
    <fullName>CityName__c</fullName>
    <label>CityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseDistrict__c.field-meta.xml
<CustomField>
    <fullName>CourseDistrict__c</fullName>
    <description>מחוז הקורס</description>
    <label>Course District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Center</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>North</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>South</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>National</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Jerusalem</label>
            </value>
            <value>
                <fullName>ארצי</fullName>
                <isActive>false</isActive>
                <label>ארצי</label>
            </value>
            <value>
                <fullName>דרום</fullName>
                <isActive>false</isActive>
                <label>דרום</label>
            </value>
            <value>
                <fullName>ירושלים</fullName>
                <isActive>false</isActive>
                <label>ירושלים</label>
            </value>
            <value>
                <fullName>מרכז</fullName>
                <isActive>false</isActive>
                <label>מרכז</label>
            </value>
            <value>
                <fullName>צפון</fullName>
                <isActive>false</isActive>
                <label>צפון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/InstitutionNickname__c.field-meta.xml
<CustomField>
    <fullName>InstitutionNickname__c</fullName>
    <label>כינוי מוסד הכשרה</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/IsStatusActive__c.field-meta.xml
<CustomField>
    <fullName>IsStatusActive__c</fullName>
    <formula>OR(
 RecordType.DeveloperName = &apos;Digital_Course&apos;,
 OR(
    ISPICKVAL(Status__c , &apos;תכנון&apos;),
    ISPICKVAL(Status__c , &apos;גיוס מועמדים&apos;)
 )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsStatusActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/ProfessionCourse__c.field-meta.xml
<CustomField>
    <fullName>ProfessionCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם מגמה</label>
    <referenceTo>ProfessionCourse__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/ProgramName__c.field-meta.xml
<CustomField>
    <fullName>ProgramName__c</fullName>
    <formula>Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProgramName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDate_Estimated__c.field-meta.xml
<CustomField>
    <fullName>StartDate_Estimated__c</fullName>
    <label>מועד פתיחה משוער</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StatusText__c.field-meta.xml
<CustomField>
    <fullName>StatusText__c</fullName>
    <formula>IF(
 IsStatusActive__c = true,
 &apos;הרשמה פתוחה&apos;,
 &apos;הרשמה נסגרה&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>StatusText</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StudiesType__c.field-meta.xml
<CustomField>
    <fullName>StudiesType__c</fullName>
    <description>אופי הלימודים</description>
    <label>Studies Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Frontal</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Online</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Hybrid</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Digital</label>
            </value>
            <value>
                <fullName>דיגיטלי</fullName>
                <isActive>false</isActive>
                <label>דיגיטלי</label>
            </value>
            <value>
                <fullName>היברידי</fullName>
                <isActive>false</isActive>
                <label>היברידי</label>
            </value>
            <value>
                <fullName>מקוון</fullName>
                <isActive>false</isActive>
                <label>מקוון</label>
            </value>
            <value>
                <fullName>פרונטלי</fullName>
                <isActive>false</isActive>
                <label>פרונטלי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Timing__c.field-meta.xml
<CustomField>
    <fullName>Timing__c</fullName>
    <description>תזמון לימודים</description>
    <label>Timing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Morning</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Evening</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Self Study</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Semesterial</label>
            </value>
            <value>
                <fullName>עצמי</fullName>
                <isActive>false</isActive>
                <label>לימוד עצמי</label>
            </value>
            <value>
                <fullName>בוקר</fullName>
                <isActive>false</isActive>
                <label>לימודי בוקר</label>
            </value>
            <value>
                <fullName>ערב</fullName>
                <isActive>false</isActive>
                <label>לימודי ערב</label>
            </value>
            <value>
                <fullName>סמסטריאלי</fullName>
                <isActive>false</isActive>
                <label>סמסטריאלי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>קורס</label>
</RecordType>

force-app/main/default/objects/Course__c/recordTypes/Digital_Course.recordType-meta.xml
<RecordType>
    <fullName>Digital_Course</fullName>
    <active>true</active>
    <label>קורס דיגיטלי</label>
</RecordType>

force-app/main/default/objects/CourseContact__c/CourseContact__c.object-meta.xml
<CustomObject>
    <label>פניה לקורס</label>
    <nameField>
        <displayFormat>A{000000000}</displayFormat>
        <label>מזהה פניה לקורס</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>פניות לקורס</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CourseContact__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>פניות לקורס</relationshipLabel>
    <relationshipName>ContactCourses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseContact__c/fields/ProfessionCourse__c.field-meta.xml
<CustomField>
    <fullName>ProfessionCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מגמה</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>ProfessionCourse__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Profession</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ProfessionCourse__c</referenceTo>
    <relationshipLabel>פניות לקורס</relationshipLabel>
    <relationshipName>ProfessionCourse</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/ProfessionCourse__c.object-meta.xml
<CustomObject>
    <label>מגמה</label>
    <nameField>
        <label>שם עיסוק/מגמה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מגמות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProfessionCourse__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>תחומים שער לקריירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionDomain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>שם קורס לחיפוש</description>
    <label>שם חלופי</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/StudiesScope__c.field-meta.xml
<CustomField>
    <fullName>StudiesScope__c</fullName>
    <label>היקף שעות</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>תגיות</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>לינק לעמוד הקורס
לקורסים דיגיטליים בלבד</description>
    <label>קישור לקורס</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/ProfessionDomain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>בניין וסביבה</fullName>
    </customValue>
    <customValue>
        <fullName>מחשבים</fullName>
    </customValue>
    <customValue>
        <fullName>תחבורה</fullName>
    </customValue>
    <customValue>
        <fullName>דפוס צילום והפקה</fullName>
    </customValue>
    <customValue>
        <fullName>טיפוח החן</fullName>
    </customValue>
    <customValue>
        <fullName>הצלה ומקצועות ימיים</fullName>
    </customValue>
    <customValue>
        <fullName>מינהל</fullName>
    </customValue>
    <customValue>
        <fullName>חינוך וטיפול</fullName>
    </customValue>
    <customValue>
        <fullName>מערכות אנרגיה ומים</fullName>
    </customValue>
    <customValue>
        <fullName>מתכת/מכונות</fullName>
    </customValue>
    <customValue>
        <fullName>רכב</fullName>
    </customValue>
    <customValue>
        <fullName>הארחה</fullName>
    </customValue>
    <customValue>
        <fullName>חשמל ואלקטרוניקה</fullName>
    </customValue>
    <customValue>
        <fullName>אופנה וטקסטיל</fullName>
    </customValue>
    <customValue>
        <fullName>עץ</fullName>
    </customValue>
    <customValue>
        <fullName>פרה-רפואי</fullName>
    </customValue>
    <customValue>
        <fullName>שונות</fullName>
    </customValue>
    <customValue>
        <fullName>מקצועות יהדות</fullName>
    </customValue>
    <customValue>
        <fullName>תעשייה וניהול</fullName>
    </customValue>
    <customValue>
        <fullName>חקלאות ונוי</fullName>
    </customValue>
    <customValue>
        <fullName>הוראה</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות</fullName>
    </customValue>
    <customValue>
        <fullName>נגישות</fullName>
    </customValue>
    <customValue>
        <fullName>קידום נשים</fullName>
    </customValue>
    <customValue>
        <fullName>מלאכה</fullName>
    </customValue>
    <customValue>
        <fullName>מיומנויות משרד</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות עברית</fullName>
    </customValue>
    <customValue>
        <fullName>ניהול קריירה</fullName>
    </customValue>
    <customValue>
        <fullName>יישומי מחשב</fullName>
    </customValue>
    <customValue>
        <fullName>שפות</fullName>
    </customValue>
    <masterLabel>ענף</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ctrl_Courses.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-09-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-09-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public class Ctrl_Courses{
	
    public Ctrl_Courses (){ getMeta(); }
    public final String coursesUrl = (string)Global_Settings__c.getAll().get('CoursesURL').get('Value__c'); //'https://courses.labor.gov.il'; 
    
    public String anchorElement;
    public String originalUrl {set;get;}
    public String title {set;get;}
    public String description {set;get;}
    public String favicon {set;get;}
    public String canonicalUrl {set;get;}
    public Map<String, String> pageParams {get; set;}
    
    //public Ctrl_Courses (CTRL ctrl){ getMeta();}
    public void getMeta(){
        
        title = Label.SiteCourses_Title;
        description = Label.SiteCourses_Description;
        
        PageReference currentPage = Apexpages.CurrentPage();
        pageParams = currentPage.getParameters();
        originalUrl = Site.getOriginalUrl();
        Utils.log(originalUrl);
        String base64Url = currentPage.getParameters().get('number');
        if(String.isNotBlank(base64Url)){
            originalUrl = EncodingUtil.base64Decode(base64Url).toString();
        }
        
        system.debug(originalUrl);
        if(String.isNotBlank(base64Url) && originalUrl.indexOf(';') > -1){
            originalUrl = originalUrl.substring(0, originalUrl.indexOf(';'));
        }
        canonicalUrl = coursesUrl;
        canonicalUrl += originalUrl != null ? originalUrl : '';
        originalUrl = String.isNotBlank(originalUrl) && originalUrl.startsWith('/') ? originalUrl.substring(1) : originalUrl;
        system.debug(originalUrl);
    }
    
    @RemoteAction
    public static List<Course> getCourses(){
        List<String> fields = new List<String>();
        fields.Add('name');
		fields.Add('ProfessionCourse__r.Url__c');
        fields.Add('ProfessionCourse__r.Nickname__c');
        fields.Add('ProfessionCourse__r.Tags__c');
        fields.Add('StudiesType__c');
        fields.Add('CityName__c');
        fields.Add('CourseDistrict__c');
        fields.Add('ProgramName__c');
        fields.Add('lastModifiedDate');
        fields.Add('ProfessionCourse__r.StudiesScope__c');
        fields.Add('InstitutionNickname__c');
        fields.Add('Timing__c');
        fields.Add('toLabel(Timing__c) timingLabel');
        fields.Add('ProfessionCourse__r.Name');
        fields.Add('toLabel(ProfessionCourse__r.Domain__c)');
        fields.Add('City__r.Name');
        fields.Add('StartDate_Estimated__c');
        fields.Add('StatusText__c');
        fields.Add('IsStatusActive__c');
        fields.Add('toLabel(PopulationType__c)');
        fields.Add('ProfessionCourse__r.Details__c');
        fields.Add('ProfessionCourse__r.SyllabusUrlFormula__c');
        fields.Add('RecordType.DeveloperName');
        DateTime dtnow = DateTime.now();
        DateTime dtStartOfMonth = DateTime.newInstance(dtnow.year(), dtnow.month(), 1);
        String dnowStr = String.valueOf(dtStartOfMonth.date());
        List<Course__c> openCourses = DAL_Courses.getCourses(' , ' + String.join(fields, ', '), 
                                                         ' where IsForWebsite__c = true and IsStatusActive__c = true and (StartDate_Estimated__c >= ' 
                                                         +  dnowStr 
                                                         + ' OR RecordType.DeveloperName = \'Digital_Course\')' );
        
        List<Course__c> closedCourses = DAL_Courses.getCourses(' , ' + String.join(fields, ', '), 
                                                         ' where IsForWebsite__c = true and IsStatusActive__c = false ' );
        
        List<Course__c> courses = new List<Course__c>(openCourses);
        courses.AddAll(closedCourses);
            
        return getCoursesCustom(courses);
    }
    
    @RemoteAction
    public static Id contact(String courseContactJson){
        if(courseContactJson != null){
            CourseContact courseContactCustom = (CourseContact) Json.deserialize(courseContactJson, CourseContact.class);
        	CourseContact__c cc = courseContactCustom.getObject();
            insert cc;
            return cc.Id;   
        }
        else{
            return null;
        }
    }
    
    public Class CourseContact{
        
        public String courseId {get; set;}
        public String contactName {get; set;} 
        public String contactPhone {get; set;}
        public String contactEmail {get; set;}
        public Boolean mailingConfirmation {get; set;}
        
        public CourseContact(){}
        public CourseContact__c getObject(){
            CourseContact__c cc = new CourseContact__c();
            cc.Course__c = this.courseId;
            cc.ContactName__c = this.contactName;
			cc.ContactPhone__c = this.contactPhone;
			cc.ContactEmail__c = this.contactEmail;            
            cc.Mailing_confirmation__c = this.mailingConfirmation != null && this.mailingConfirmation == true ? true : false;
            cc.ProfessionCourse__c = getProfessionCourseId();
            return cc;
        }

        private Id getProfessionCourseId(){
            return [SELECT ProfessionCourse__c FROM Course__c WHERE Id =: this.courseId Limit 1].ProfessionCourse__c;
        }
    }
    
    public Class Course{
        public String id {get; set;}
        public String name {get; set;} 
        public String scope {get; set;} // תחום
        public String city {get; set;} // מיקום גיאוגרפי
        public String tags {get; set;} // תגיות
        public DateTime startDate {get; set;}
        public String audience {get; set;} // קהל יעד
        public String scopeOfActivity {get; set;} //היקף פעילות
        public String learningHours {get; set;} //שעות לימוד
        public String learningHoursLabel {get; set;} //שעות לימוד
        public String academyName {get; set;} //שם מכללה
        public String details {get; set;} 
        public String silabusUrl {get; set;}
        public String studiesType {get; set;} //אופי הלימודים
        public String programName {get; set;} //תוכנית הכשרה
        public String district {get; set;} //מחוז
        public String nickname {get; set;} 
        public String courseUrl {get; set;}
        public String statusText {get; set;}
        public Boolean isStatusActive {get; set;}
        public String startDateDigital {get; set;}
        
        public Course(){}
        public Course(Course__c c){
            this.id = c.Id;
            if(c.ProfessionCourse__r != null){
                this.name = c.ProfessionCourse__r.Name;
                this.details = c.ProfessionCourse__r.Details__c;
            	this.scope = c.ProfessionCourse__r.Domain__c;
                this.tags = c.ProfessionCourse__r.Tags__c;
                this.scopeOfActivity = c.ProfessionCourse__r.StudiesScope__c != null ? String.valueOf(c.ProfessionCourse__r.StudiesScope__c) + ' שעות': null;// היקף שעות
                this.silabusUrl = c.ProfessionCourse__r.SyllabusUrlFormula__c;// empty
                this.nickname = c.ProfessionCourse__r.Nickname__c;
                this.courseUrl = c.ProfessionCourse__r.Url__c;
            }
            
            this.city = c.City__r != null ? c.City__r.Name : c.CityName__c; //empty
            this.startDate = c.StartDate_Estimated__c;
            this.audience = c.PopulationType__c;
            this.learningHours = c.Timing__c;
            this.learningHoursLabel = (string) c.get('timingLabel');
            this.academyName = c.InstitutionNickname__c;
            this.studiesType = c.StudiesType__c;
            this.programName = c.ProgramName__c;//empty
            this.district = c.CourseDistrict__c;
            this.statusText = c.StatusText__c;
            this.isStatusActive = c.IsStatusActive__c;
            
            if(c.RecordType.DeveloperName == 'Digital_Course'){
                this.studiesType = 'מקוון';
                this.city = 'מקוון';
                this.academyName = 'קמפוס IL';
                this.startDateDigital = 'זמין בכל עת';
                DateTime tmp = DateTime.now().addMonths(1);
                this.startDate = tmp;
                this.learningHoursLabel = 'לימוד עצמי';
                this.learningHours = 'עצמי';
                if(String.isBlank(this.audience)){
                   this.audience = 'אוכלוסיה כללית'; 
                }
            }
        }
    }
    
    
    public static List<Course> getCoursesCustom(List<Course__c> lst){
        Utils.log(lst);
        List<Course> result = new List<Course>();
        if(lst != null){
            for(Course__c c : lst){
                result.add(new Course(c));
            }
        }
        utils.log(result);
        return result;
    }
    
    @RemoteAction
    public static List<SiteUtils.ConfigField> getCoursesConfig(){
        List<SiteUtils.ConfigField> configLst = new List<SiteUtils.ConfigField>();
        configLst.add(new SiteUtils.ConfigDropdown('scope', 'תחום', null, Utils.getListLabelValue(ProfessionCourse__c.Domain__c.getDescribe().getPicklistValues())));
        configLst.add(new SiteUtils.ConfigDropdown('district', 'אזור גאוגרפי', null, Utils.getListLabelValue(Course__c.CourseDistrict__c.getDescribe().getPicklistValues())));
        configLst.add(new SiteUtils.ConfigDropdown('audience', 'קהל יעד', null, Utils.getListLabelValue(Course__c.PopulationType__c.getDescribe().getPicklistValues())));
        configLst.add(new SiteUtils.ConfigDropdown('learningHours', 'שעות לימוד', null, Utils.getListLabelValue(Course__c.Timing__c.getDescribe().getPicklistValues())));
        configLst.add(new SiteUtils.ConfigDropdown( 'statusText', 'סטטוס הרשמה', null, new List<Utils.LabelValue>{
        	new Utils.LabelValue('הרשמה פתוחה', 'הרשמה פתוחה'),
            new Utils.LabelValue('הרשמה נסגרה', 'הרשמה נסגרה')
        }));
        return configLst;
    }
}