force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <displayFormat>C-{000000000}</displayFormat>
        <label>מזהה קורס</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/AbsorbedNumber__c.field-meta.xml
<CustomField>
    <fullName>AbsorbedNumber__c</fullName>
    <label>כמות נקלטים לקורס</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CandidatesNumber__c.field-meta.xml
<CustomField>
    <fullName>CandidatesNumber__c</fullName>
    <label>כמות מועמדים</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CityName__c.field-meta.xml
<CustomField>
    <fullName>CityName__c</fullName>
    <label>CityName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseDistrict__c.field-meta.xml
<CustomField>
    <fullName>CourseDistrict__c</fullName>
    <description>מחוז הקורס</description>
    <label>Course District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Center</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>North</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>South</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>National</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Jerusalem</label>
            </value>
            <value>
                <fullName>ארצי</fullName>
                <isActive>false</isActive>
                <label>ארצי</label>
            </value>
            <value>
                <fullName>דרום</fullName>
                <isActive>false</isActive>
                <label>דרום</label>
            </value>
            <value>
                <fullName>ירושלים</fullName>
                <isActive>false</isActive>
                <label>ירושלים</label>
            </value>
            <value>
                <fullName>מרכז</fullName>
                <isActive>false</isActive>
                <label>מרכז</label>
            </value>
            <value>
                <fullName>צפון</fullName>
                <isActive>false</isActive>
                <label>צפון</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>הערות</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/InstitutionNickname__c.field-meta.xml
<CustomField>
    <fullName>InstitutionNickname__c</fullName>
    <label>כינוי מוסד הכשרה</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/isInPublicSite__c.field-meta.xml
<CustomField>
    <fullName>isInPublicSite__c</fullName>
    <defaultValue>true</defaultValue>
    <label>תצוגה באתר</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/IsTvaIncluded__c.field-meta.xml
<CustomField>
    <fullName>IsTvaIncluded__c</fullName>
    <defaultValue>true</defaultValue>
    <label>מע&quot;מ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/PopulationType__c.field-meta.xml
<CustomField>
    <fullName>PopulationType__c</fullName>
    <description>קהל יעד</description>
    <label>Population Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>General Public</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Haredit community</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Haredim Soldiers</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Civilian Service</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Arabic community</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>With Disablities</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>Risk Youth</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>Singular Parents</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>Welfare population</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Ethiopian Immigrants</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Soldiers</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Senior Nursery Worker</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Prisoners</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>New Immigrants</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>BackInQuestion Population</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Women</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Age 45+</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>General Crowd</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>Has Backround</label>
            </value>
            <value>
                <fullName>אוכלוסיית יוצאים בשאלה</fullName>
                <isActive>false</isActive>
                <label>אוכלוסיית יוצאים בשאלה</label>
            </value>
            <value>
                <fullName>אוכלוסיית רווחה</fullName>
                <isActive>false</isActive>
                <label>אוכלוסיית רווחה</label>
            </value>
            <value>
                <fullName>אנשים עם מוגבלות</fullName>
                <isActive>false</isActive>
                <label>אנשים עם מוגבלות</label>
            </value>
            <value>
                <fullName>אסירים</fullName>
                <isActive>false</isActive>
                <label>אסירים</label>
            </value>
            <value>
                <fullName>בעלי רקע בתחום</fullName>
                <isActive>false</isActive>
                <label>בעלי רקע בתחום</label>
            </value>
            <value>
                <fullName>גילאי 45+</fullName>
                <isActive>false</isActive>
                <label>גילאי 45+</label>
            </value>
            <value>
                <fullName>הורים יחידים</fullName>
                <isActive>false</isActive>
                <label>הורים יחידים</label>
            </value>
            <value>
                <fullName>הציבור הרחב</fullName>
                <isActive>false</isActive>
                <label>הציבור הרחב</label>
            </value>
            <value>
                <fullName>חברה חרדית</fullName>
                <isActive>false</isActive>
                <label>חברה חרדית</label>
            </value>
            <value>
                <fullName>חברה ערבית</fullName>
                <isActive>false</isActive>
                <label>חברה ערבית</label>
            </value>
            <value>
                <fullName>חיילים</fullName>
                <isActive>false</isActive>
                <label>חיילים</label>
            </value>
            <value>
                <fullName>עולים חדשים</fullName>
                <isActive>false</isActive>
                <label>עולים חדשים</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/ProfessionCourse__c.field-meta.xml
<CustomField>
    <fullName>ProfessionCourse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>שם מגמה</label>
    <referenceTo>ProfessionCourse__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StartDate_Estimated__c.field-meta.xml
<CustomField>
    <fullName>StartDate_Estimated__c</fullName>
    <label>מועד פתיחה משוער</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StudentsCount__c.field-meta.xml
<CustomField>
    <fullName>StudentsCount__c</fullName>
    <label>כמות מסיימים</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/StudiesType__c.field-meta.xml
<CustomField>
    <fullName>StudiesType__c</fullName>
    <description>אופי הלימודים</description>
    <label>Studies Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Frontal</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Online</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Hybrid</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Digital</label>
            </value>
            <value>
                <fullName>דיגיטלי</fullName>
                <isActive>false</isActive>
                <label>דיגיטלי</label>
            </value>
            <value>
                <fullName>היברידי</fullName>
                <isActive>false</isActive>
                <label>היברידי</label>
            </value>
            <value>
                <fullName>מקוון</fullName>
                <isActive>false</isActive>
                <label>מקוון</label>
            </value>
            <value>
                <fullName>פרונטלי</fullName>
                <isActive>false</isActive>
                <label>פרונטלי</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Global_Settings__c/Global_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Global Settings</label>
</CustomObject>

force-app/main/default/objects/ProfessionCourse__c/ProfessionCourse__c.object-meta.xml
<CustomObject>
    <label>מגמה</label>
    <nameField>
        <label>שם עיסוק/מגמה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מגמות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProfessionCourse__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>קוד מגמה</description>
    <externalId>true</externalId>
    <label>קוד מגמה</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>תיאור מגמה</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>תחומים שער לקריירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionDomain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>שם קורס לחיפוש</description>
    <label>שם חלופי</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Numeric_index__c.field-meta.xml
<CustomField>
    <fullName>Numeric_index__c</fullName>
    <description>קוד מספרי</description>
    <externalId>true</externalId>
    <label>קוד ממשל זמין</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/SyllabusUrl__c.field-meta.xml
<CustomField>
    <fullName>SyllabusUrl__c</fullName>
    <label>קישור לסילבוס</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Tags__c.field-meta.xml
<CustomField>
    <fullName>Tags__c</fullName>
    <label>תגיות</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>לינק לעמוד הקורס
לקורסים דיגיטליים בלבד</description>
    <label>קישור לקורס</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/ProfessionDomain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>בניין וסביבה</fullName>
    </customValue>
    <customValue>
        <fullName>מחשבים</fullName>
    </customValue>
    <customValue>
        <fullName>תחבורה</fullName>
    </customValue>
    <customValue>
        <fullName>דפוס צילום והפקה</fullName>
    </customValue>
    <customValue>
        <fullName>טיפוח החן</fullName>
    </customValue>
    <customValue>
        <fullName>הצלה ומקצועות ימיים</fullName>
    </customValue>
    <customValue>
        <fullName>מינהל</fullName>
    </customValue>
    <customValue>
        <fullName>חינוך וטיפול</fullName>
    </customValue>
    <customValue>
        <fullName>מערכות אנרגיה ומים</fullName>
    </customValue>
    <customValue>
        <fullName>מתכת/מכונות</fullName>
    </customValue>
    <customValue>
        <fullName>רכב</fullName>
    </customValue>
    <customValue>
        <fullName>הארחה</fullName>
    </customValue>
    <customValue>
        <fullName>חשמל ואלקטרוניקה</fullName>
    </customValue>
    <customValue>
        <fullName>אופנה וטקסטיל</fullName>
    </customValue>
    <customValue>
        <fullName>עץ</fullName>
    </customValue>
    <customValue>
        <fullName>פרה-רפואי</fullName>
    </customValue>
    <customValue>
        <fullName>שונות</fullName>
    </customValue>
    <customValue>
        <fullName>מקצועות יהדות</fullName>
    </customValue>
    <customValue>
        <fullName>תעשייה וניהול</fullName>
    </customValue>
    <customValue>
        <fullName>חקלאות ונוי</fullName>
    </customValue>
    <customValue>
        <fullName>הוראה</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות</fullName>
    </customValue>
    <customValue>
        <fullName>נגישות</fullName>
    </customValue>
    <customValue>
        <fullName>קידום נשים</fullName>
    </customValue>
    <customValue>
        <fullName>מלאכה</fullName>
    </customValue>
    <customValue>
        <fullName>מיומנויות משרד</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות עברית</fullName>
    </customValue>
    <customValue>
        <fullName>ניהול קריירה</fullName>
    </customValue>
    <customValue>
        <fullName>יישומי מחשב</fullName>
    </customValue>
    <customValue>
        <fullName>שפות</fullName>
    </customValue>
    <masterLabel>ענף</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TEST_Courses.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-20-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-18-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class TEST_Courses {
    
    static TestMethod void testCourses(){
    	Test.startTest();
        insert new Global_Settings__c(Name = 'CoursesURL', Value__c = 'https://courses.labor.gov.il');	
        Ctrl_Courses ctrl = new Ctrl_Courses();
        List<ProfessionCourse__c> profCourses = getProfessionCourses(100);
        system.debug('///profCourses: ' + profCourses);
        insert profCourses;
        List<Course__c> courses = getCourses(100, profCourses);
        system.debug('///courses: ' + courses);
        insert courses;
        Ctrl_Courses.getCourses();
        
        Ctrl_Courses.CourseContact cc = new Ctrl_Courses.CourseContact();
        cc.contactEmail = 's@s.com';
        cc.contactName = 'test';
        cc.contactPhone = '0585858588';
        cc.courseId = courses[0].Id;
        cc.mailingConfirmation = true;
        Ctrl_Courses.contact(json.serialize(cc));
        
        Ctrl_Courses.getCoursesConfig();
        
        List<Utils.LabelValue> options = Utils.getListLabelValue(Course__c.CourseDistrict__c.getDescribe().getPicklistValues());
        Set<Utils.LabelValue> optionsSet = new Set<Utils.LabelValue>(options);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', optionsSet);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options, 'valueOther');
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options, 'valueOther', false);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', optionsSet, 'valueOther', false);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options, 'valueOther', false, true);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', optionsSet, 'valueOther', false,true);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options, 'valueOther', false, true, true);
        new SiteUtils.ConfigDropdown('apiName', 'label', 'tooltip', options, '', false);
        new SiteUtils.ConfigSort('district', 'אזור גאוגרפי', 'name', '', false);
        new SiteUtils.ConfigSort('district', 'אזור גאוגרפי', 'name', '');
        new SiteUtils.ConfigCheckbox('apiName', 'label', 'tooltip');
        new SiteUtils.ConfigCheckbox('apiName', 'label', 'tooltip', 'category', false);
        new SiteUtils.ConfigSlider('apiName', 'label', 'tooltip', 0, 2);
        new SiteUtils.ConfigSlider('apiName', 'label', 'tooltip', options);
        new SiteUtils.ConfigSlider('apiName', 'label', 'tooltip', options, '', false);
        
        new SiteUtils.ConfigAutoComplete('apiName', 'label', 'tooltip', 'functionFullName', 'functionReverseFullName');
        new SiteUtils.ConfigAutoComplete('apiName', 'label', 'tooltip', 'functionFullName', 'functionReverseFullName', 'category', true);
        
        Test.stopTest();
    }
    
    static List<ProfessionCourse__c> getProfessionCourses(integer counter){
        List<ProfessionCourse__c> lst = new List<ProfessionCourse__c>();
        for(integer i = 0 ; i < counter ; i++){
            ProfessionCourse__c tmp = new ProfessionCourse__c();
            tmp.Name = 'Test';
            tmp.Code__c = String.valueOf(i);
            tmp.Details__c = String.valueOf(i);
            tmp.Nickname__c = String.valueOf(i);
            tmp.Numeric_index__c = i;
            tmp.SyllabusUrl__c = String.valueOf(i);
            tmp.Tags__c = String.valueOf(i);
            tmp.Url__c = String.valueOf(i);
            tmp.Domain__c = 'הוראה';
            
            lst.Add(tmp);
        }
        return lst;
    }
	
    
    static List<Course__c> getCourses(integer counter, List<ProfessionCourse__c> profCourses){
        List<Course__c> lst = new List<Course__c>();
        for(integer i = 0 ; i < counter && i < profCourses.size() ; i++){
            Course__c tmp = new Course__c();
            // tmp.Name = 'Test';
            tmp.CityName__c = String.valueOf(i);
            tmp.Details__c = String.valueOf(i);
            tmp.PopulationType__c = 'עולים חדשים';
            tmp.StudiesType__c = 'פרונטלי';
            tmp.IsTvaIncluded__c = true;
            tmp.InstitutionNickname__c = String.valueOf(i);
            tmp.CandidatesNumber__c = i;
            tmp.StudentsCount__c = i;
            tmp.AbsorbedNumber__c = i;
            tmp.isInPublicSite__c = true;
            tmp.ProfessionCourse__c = profCourses[i].Id;
            tmp.CourseDistrict__c = 'דרום';
            tmp.StartDate_Estimated__c = System.today();
            
            
            lst.Add(tmp);
        }
        return lst;
    }
}