force-app/main/default/objects/Account/fields/Affiliation_To_Application__c.field-meta.xml
<CustomField>
    <fullName>Affiliation_To_Application__c</fullName>
    <description>שיוך למערכות</description>
    <label>Affiliation To Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>זירת מעסיקים</fullName>
                <default>true</default>
                <label>זירת מעסיקים</label>
            </value>
            <value>
                <fullName>ממשק לפרט</fullName>
            </value>
            <value>
                <fullName>זירת מעסיקים וממשק לפרט</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_provider__c.field-meta.xml
<CustomField>
    <fullName>Service_provider__c</fullName>
    <description>סוג נותן שירות</description>
    <label>Service provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>יחידה של זרוע עבודה</fullName>
            </value>
            <value>
                <fullName>ספק רישוי לעיסוק</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <label>College</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Operator</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Zrua Avudas unit</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Occupation licensing provider</label>
            </value>
            <value>
                <fullName>מכללה</fullName>
            </value>
            <value>
                <fullName>מפעיל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestUtils.cls
public inherited sharing class TestUtils {
    public static List<Account> createAccounts(Integer numAccs){
		List<Account> accounts = new List<Account>();
		for (Integer i = 0; i < numAccs; i++){
			Account acc = new Account(Name = 'Test Acount '+String.valueOf(i),
				Phone = '1234567', Partner__c = true, Service_provider__c = 'מפעיל', Affiliation_To_Application__c = 'זירת מעסיקים');
			accounts.add(acc);
		}
		return accounts;
	}
}