force-app/main/default/objects/Account/fields/Affiliation_To_Application__c.field-meta.xml
<CustomField>
    <fullName>Affiliation_To_Application__c</fullName>
    <description>שיוך למערכות</description>
    <label>Affiliation To Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>זירת מעסיקים</fullName>
                <default>true</default>
                <label>זירת מעסיקים</label>
            </value>
            <value>
                <fullName>ממשק לפרט</fullName>
            </value>
            <value>
                <fullName>זירת מעסיקים וממשק לפרט</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_provider__c.field-meta.xml
<CustomField>
    <fullName>Service_provider__c</fullName>
    <description>סוג נותן שירות</description>
    <label>Service provider</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>יחידה של זרוע עבודה</fullName>
            </value>
            <value>
                <fullName>ספק רישוי לעיסוק</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <label>College</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Operator</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Zrua Avudas unit</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Occupation licensing provider</label>
            </value>
            <value>
                <fullName>מכללה</fullName>
            </value>
            <value>
                <fullName>מפעיל</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>עיר</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ערים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/ProfessionCourse__c.object-meta.xml
<CustomObject>
    <label>מגמה</label>
    <nameField>
        <label>שם עיסוק/מגמה</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מגמות</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProfessionCourse__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>קוד מגמה</description>
    <externalId>true</externalId>
    <label>קוד מגמה</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>תחומים שער לקריירה</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionDomain</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/OJT__c.field-meta.xml
<CustomField>
    <fullName>OJT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OJT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProfessionCourse__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>ענף</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>בניין וסביבה</fullName>
            </value>
            <value>
                <fullName>מחשבים</fullName>
            </value>
            <value>
                <fullName>תחבורה</fullName>
            </value>
            <value>
                <fullName>דפוס צילום והפקה</fullName>
            </value>
            <value>
                <fullName>טיפוח החן</fullName>
            </value>
            <value>
                <fullName>הצלה ומקצועות ימיים</fullName>
            </value>
            <value>
                <fullName>מינהל</fullName>
            </value>
            <value>
                <fullName>חינוך וטיפול</fullName>
            </value>
            <value>
                <fullName>מערכות אנרגיה ומים</fullName>
            </value>
            <value>
                <fullName>מתכת/מכונות</fullName>
            </value>
            <value>
                <fullName>רכב</fullName>
            </value>
            <value>
                <fullName>הארחה</fullName>
            </value>
            <value>
                <fullName>חשמל ואלקטרוניקה</fullName>
            </value>
            <value>
                <fullName>אופנה וטקסטיל</fullName>
            </value>
            <value>
                <fullName>עץ</fullName>
            </value>
            <value>
                <fullName>פרה-רפואי</fullName>
            </value>
            <value>
                <fullName>שונות</fullName>
            </value>
            <value>
                <fullName>מקצועות יהדות</fullName>
            </value>
            <value>
                <fullName>תעשייה וניהול</fullName>
            </value>
            <value>
                <fullName>חקלאות ונוי</fullName>
            </value>
            <value>
                <fullName>הוראה</fullName>
            </value>
            <value>
                <fullName>מכינות</fullName>
            </value>
            <value>
                <fullName>נגישות</fullName>
            </value>
            <value>
                <fullName>קידום נשים</fullName>
            </value>
            <value>
                <fullName>מלאכה</fullName>
            </value>
            <value>
                <fullName>מיומנויות משרד</fullName>
            </value>
            <value>
                <fullName>אחר</fullName>
            </value>
            <value>
                <fullName>אילנאות</fullName>
            </value>
            <value>
                <fullName>לוגיסטיקה</fullName>
            </value>
            <value>
                <fullName>מכונות</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Program_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Program Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/ProgramRequest__c.object-meta.xml
<CustomObject>
    <label>תכנית למעסיק</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>ProgramRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>תכניות למעסיק</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramRequest__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>for Magar is the request number</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Mail_Employer__c.field-meta.xml
<CustomField>
    <fullName>Mail_Employer__c</fullName>
    <defaultValue>true</defaultValue>
    <label>שליחת דוא&quot;ל למעסיק</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Primary_Contact_PR__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_PR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Qty_vouchers_requested__c.field-meta.xml
<CustomField>
    <fullName>Qty_vouchers_requested__c</fullName>
    <label>כמות שוברים מבוקשת</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/StatusDate__c.field-meta.xml
<CustomField>
    <fullName>StatusDate__c</fullName>
    <label>StatusDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/vouchers_approved__c.field-meta.xml
<CustomField>
    <fullName>vouchers_approved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>כמות שוברים מאושרת להקצאה</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/recordTypes/Shovar_Lamaasik.recordType-meta.xml
<RecordType>
    <fullName>Shovar_Lamaasik</fullName>
    <active>true</active>
    <label>שובר למעסיק</label>
</RecordType>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if there is only one, when the programrequest is created then also this lookup to program is filled</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Street__c/Street__c.object-meta.xml
<CustomObject>
    <label>Street</label>
    <nameField>
        <label>Street Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Streets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Street__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Streets</relationshipLabel>
    <relationshipName>Streets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Street__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher_Stock__c/fields/Initial_amount_vouchers__c.field-meta.xml
<CustomField>
    <fullName>Initial_amount_vouchers__c</fullName>
    <label>כמות שוברים התחלתית</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/fields/Qty_vouchers_requested__c.field-meta.xml
<CustomField>
    <fullName>Qty_vouchers_requested__c</fullName>
    <label>כמות שוברים שהוקצו</label>
    <summaryFilterItems>
        <field>Voucher__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Voucher__c.Voucher_Stock__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/globalValueSets/ProfessionDomain.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>בניין וסביבה</fullName>
    </customValue>
    <customValue>
        <fullName>מחשבים</fullName>
    </customValue>
    <customValue>
        <fullName>תחבורה</fullName>
    </customValue>
    <customValue>
        <fullName>דפוס צילום והפקה</fullName>
    </customValue>
    <customValue>
        <fullName>טיפוח החן</fullName>
    </customValue>
    <customValue>
        <fullName>הצלה ומקצועות ימיים</fullName>
    </customValue>
    <customValue>
        <fullName>מינהל</fullName>
    </customValue>
    <customValue>
        <fullName>חינוך וטיפול</fullName>
    </customValue>
    <customValue>
        <fullName>מערכות אנרגיה ומים</fullName>
    </customValue>
    <customValue>
        <fullName>מתכת/מכונות</fullName>
    </customValue>
    <customValue>
        <fullName>רכב</fullName>
    </customValue>
    <customValue>
        <fullName>הארחה</fullName>
    </customValue>
    <customValue>
        <fullName>חשמל ואלקטרוניקה</fullName>
    </customValue>
    <customValue>
        <fullName>אופנה וטקסטיל</fullName>
    </customValue>
    <customValue>
        <fullName>עץ</fullName>
    </customValue>
    <customValue>
        <fullName>פרה-רפואי</fullName>
    </customValue>
    <customValue>
        <fullName>שונות</fullName>
    </customValue>
    <customValue>
        <fullName>מקצועות יהדות</fullName>
    </customValue>
    <customValue>
        <fullName>תעשייה וניהול</fullName>
    </customValue>
    <customValue>
        <fullName>חקלאות ונוי</fullName>
    </customValue>
    <customValue>
        <fullName>הוראה</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות</fullName>
    </customValue>
    <customValue>
        <fullName>נגישות</fullName>
    </customValue>
    <customValue>
        <fullName>קידום נשים</fullName>
    </customValue>
    <customValue>
        <fullName>מלאכה</fullName>
    </customValue>
    <customValue>
        <fullName>מיומנויות משרד</fullName>
    </customValue>
    <customValue>
        <fullName>מכינות עברית</fullName>
    </customValue>
    <customValue>
        <fullName>ניהול קריירה</fullName>
    </customValue>
    <customValue>
        <fullName>יישומי מחשב</fullName>
    </customValue>
    <customValue>
        <fullName>שפות</fullName>
    </customValue>
    <masterLabel>ענף</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TEST_Batches.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-30-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   04-04-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
@isTest
public class TEST_Batches {

    private static string getCronString(){
        Datetime now = Datetime.now().addMinutes(2);
        Integer second = now.second();
        Integer minute = now.minute();
        Integer hour = now.hour();
        Integer day = now.day();
        Integer year = now.year();
        return '' + second + ' ' + minute + ' ' + hour + ' ' + day + ' * ? ' + year;
    }

    static TestMethod void testSyncCity(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();
        insert new City__c(Name = 'test');
        Test.setMock(HttpCalloutMock.class, new CityHttpResMockImpl());
        System.runAs(users[0]){
            System.schedule('SCHD_SyncCities'+System.now(), cronStr, new SCHD_SyncCities());
        }
        Test.stopTest(); 
    }
    
    static TestMethod void testSyncStreet(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();
        insert new City__c(Name = 'test', Code__c = '472');
        insert new Street__c(Name = 'test', Code__c = '472');
        Test.setMock(HttpCalloutMock.class, new StreetHttpResMockImpl());
        System.runAs(users[0]){
            System.schedule('SCHD_SyncStreets'+System.now(), cronStr, new SCHD_SyncStreets());
        }
        Test.stopTest(); 
    }
    
    static TestMethod void testSyncPrograms(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();
        Program__c pro = new Program__c(External_Program_Id__c = Label_Utils.programs.get('ojt'));
        insert pro;
        Request__c r = new Request__c(ExtId__c = '1234_2');
        insert r;
        insert new ProgramRequest__c(Program__c = pro.Id, Request__c = r.Id, StatusDate__c = System.now(), Mail_Employer__c = false, ExtId__c = '1234_2');
        Test.setMock(HttpCalloutMock.class, new ProgramHttpResMockImpl());
        System.runAs(users[0]){
            System.schedule('SCHD_SyncProgramsFromMagar'+System.now(), cronStr, new SCHD_SyncProgramsFromMagar());
        }
        Test.stopTest();
    }
    
    static TestMethod void testSyncProfessions(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();
        insert new Account(Name = 'test', Partner__c = true, Service_provider__c = Label_Utils.accServiceProvider.get('מפעיל'), Affiliation_To_Application__c = Label_Utils.accAffilationToApp.get('זירת מעסיקים'));
        insert new ProfessionCourse__c(Name = 'test', code__c = '1234', StatusDate__c = System.now(), Sector__c = 'מחשבים', Domain__c='מחשבים', OJT__c = true);
        Test.setMock(HttpCalloutMock.class, new ProfessionHttpResMockImpl());
        System.runAs(users[0]){
            System.schedule('SCHD_SyncProfessionsFromMagar'+System.now(), cronStr, new SCHD_SyncProfessionsFromMagar());
        }
        Test.stopTest();
    }

    static TestMethod void testEmailVoucherStock(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();

        Contact con = TEST_Utils.createTestContact(new List<Contact>{new Contact()})[0];
        insert con;
        Program__c pro = TEST_Utils.createTestProgram(new List<Program__c>{new Program__c(Name = 'שובר למעסיק')})[0];
        insert pro;
        List<Voucher_Stock__c> vouchStockList = TEST_Utils.createTestVoucherStock(new List<Voucher_Stock__c>{new Voucher_Stock__c(Initial_amount_vouchers__c = 1, Send_Email__c = true)});
        insert vouchStockList;
        Id proReqShovar_RT = Schema.SObjectType.ProgramRequest__c.getRecordTypeInfosByDeveloperName().get('Shovar_Lamaasik').getRecordTypeId();
        List<ProgramRequest__c> proReqsList = TEST_Utils.createTestProgramRequest(new List<ProgramRequest__c>{new ProgramRequest__c(RecordTypeId = proReqShovar_RT, Primary_Contact_PR__c = con.Id, Program__c = pro.Id, Voucher_Stock__c = vouchStockList[0].Id, Qty_vouchers_requested__c = 5, vouchers_approved__c = 0, Status__c = Label_Utils.programRequestStatus.get('אזל מלאי שוברים'))});
        insert proReqsList;

        System.debug('!!!pro: ' + pro);
        System.debug('!!!proReqsList: ' + proReqsList);
        Test.setMock(HttpCalloutMock.class, new ProfessionHttpResMockImpl());
        System.runAs(users[0]){
            System.schedule('SCHD_sendEmailVoucherStock'+System.now(), cronStr, new SCHD_sendEmailVoucherStock());
        }
        Test.stopTest();
    }
    
    static TestMethod void testResetFieldOnceAYear(){
        List<User> users = [SELECT Id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true];
        String cronStr = getCronString();
        Test.startTest();

        Account acc = TEST_Utils.createTestAccount(new List<Account>{new Account(Expired_Vouchers_Counter__c = 16)})[0];
        insert acc;
		System.debug('!!!acc: ' + acc);
        Test.setMock(HttpCalloutMock.class, new ProfessionHttpResMockImpl());
        System.runAs(users[0]){
            System.debug('!!!insert');
            System.schedule('SCHD_ResetFieldOnceAYear'+System.now(), cronStr, new SCHD_ResetFieldOnceAYear());
        }
        Test.stopTest();
    }
}