force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/External_Program_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Program_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Program Id</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>עתידית</fullName>
            </value>
            <value>
                <fullName>בהקמה</fullName>
            </value>
            <value>
                <fullName>פעילה</fullName>
            </value>
            <value>
                <fullName>מוקפאת</fullName>
            </value>
            <value>
                <fullName>הסתיימה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/ProgramRequest__c.object-meta.xml
<CustomObject>
    <label>תכנית למעסיק</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>ProgramRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>תכניות למעסיק</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramRequest__c/fields/API__c.field-meta.xml
<CustomField>
    <fullName>API__c</fullName>
    <defaultValue>false</defaultValue>
    <label>מגיע מממשק</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/ExtId__c.field-meta.xml
<CustomField>
    <fullName>ExtId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>for Magar is the request number</description>
    <externalId>true</externalId>
    <label>ExtId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Mail_Employer__c.field-meta.xml
<CustomField>
    <fullName>Mail_Employer__c</fullName>
    <defaultValue>true</defaultValue>
    <label>שליחת דוא&quot;ל למעסיק</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
            </value>
            <value>
                <fullName>נוצר קשר טלפוני עם המעסיק</fullName>
            </value>
            <value>
                <fullName>קיבל פרטים, שוקל הצטרפות</fullName>
            </value>
            <value>
                <fullName>מילא טפסים- בתהליך הצטרפות</fullName>
            </value>
            <value>
                <fullName>איסוף צרכים מהמעסיק</fullName>
            </value>
            <value>
                <fullName>השלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>נחתם הסכם עם המעסיק</fullName>
            </value>
            <value>
                <fullName>המעסיק הצטרף להכשרה קיימת</fullName>
            </value>
            <value>
                <fullName>גיבוש קבוצת מעסיקים</fullName>
            </value>
            <value>
                <fullName>הושלם תהליך הגיוס</fullName>
            </value>
            <value>
                <fullName>המעסיק לא מעוניין להצטרף</fullName>
            </value>
            <value>
                <fullName>הבקשה נדחתה</fullName>
            </value>
            <value>
                <fullName>אושר</fullName>
            </value>
            <value>
                <fullName>טיפול בערעור</fullName>
            </value>
            <value>
                <fullName>בטיפול המשרד</fullName>
            </value>
            <value>
                <fullName>תקציב נגמר</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים מלאה</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים חלקית</fullName>
            </value>
            <value>
                <fullName>אזל מלאי שוברים</fullName>
            </value>
            <value>
                <fullName>הושלם</fullName>
                <isActive>false</isActive>
                <label>הושלם</label>
            </value>
            <value>
                <fullName>המלצת רכז</fullName>
                <isActive>false</isActive>
                <label>המלצת רכז</label>
            </value>
            <value>
                <fullName>הצטרף לתוכנית</fullName>
                <isActive>false</isActive>
                <label>הצטרף לתוכנית</label>
            </value>
            <value>
                <fullName>לא מתאים</fullName>
                <isActive>false</isActive>
                <label>לא מתאים</label>
            </value>
            <value>
                <fullName>נדחה</fullName>
                <isActive>false</isActive>
                <label>נדחה</label>
            </value>
            <value>
                <fullName>נוצר קשר ע&quot;י התוכנית</fullName>
                <isActive>false</isActive>
                <label>נוצר קשר ע&quot;י התוכנית</label>
            </value>
            <value>
                <fullName>סיים את התוכנית</fullName>
                <isActive>false</isActive>
                <label>סיים את התוכנית</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/recordTypes/OJT_Recommendation.recordType-meta.xml
<RecordType>
    <fullName>OJT_Recommendation</fullName>
    <active>true</active>
    <label>הכשרה בעבודה</label>
</RecordType>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Closing_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closing_Reason__c</fullName>
    <label>Closing Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>לא ניתן ליצור קשר</fullName>
            </value>
            <value>
                <fullName>המעסיק חזר בו מפנייתו</fullName>
            </value>
            <value>
                <fullName>לא נמצאה תוכנית מתאימה</fullName>
            </value>
            <value>
                <fullName>בקשה כפולה</fullName>
            </value>
            <value>
                <fullName>לא רלוונטי</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול בתוכנית</fullName>
                <label>מיפוי בוצע בהצלחה</label>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
                <isActive>false</isActive>
                <label>הועבר לטיפול המפעיל</label>
            </value>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
                <isActive>false</isActive>
                <label>הועבר למילוי טפסים</label>
            </value>
            <value>
                <fullName>לא ניתנה המלצה</fullName>
                <isActive>false</isActive>
                <label>לא ניתנה המלצה</label>
            </value>
            <value>
                <fullName>נתונים שגויים</fullName>
                <isActive>false</isActive>
                <label>נתונים שגויים</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Employees_Requested_Num__c.field-meta.xml
<CustomField>
    <fullName>Employees_Requested_Num__c</fullName>
    <label>Employees Requested Num</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Job__c.field-meta.xml
<CustomField>
    <fullName>Job__c</fullName>
    <label>Job</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/JSON__c.field-meta.xml
<CustomField>
    <fullName>JSON__c</fullName>
    <label>JSON</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if there is only one, when the programrequest is created then also this lookup to program is filled</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Request_Details__c</fullName>
    <label>Request Details</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Number__c.field-meta.xml
<CustomField>
    <fullName>Request_Number__c</fullName>
    <label>Request Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>Complete_Info</fullName>
                <label>השלמת פרטים</label>
            </value>
            <value>
                <fullName>Needs_mapping</fullName>
                <label>מיפוי צרכים</label>
            </value>
            <value>
                <fullName>programRequest</fullName>
                <label>המלצה לתכנית</label>
            </value>
            <value>
                <fullName>CloseRequest</fullName>
                <label>סגירת בקשה</label>
            </value>
            <value>
                <fullName>סגור</fullName>
            </value>
            <value>
                <fullName>לא נמצאה תכנית מתאימה</fullName>
                <isActive>false</isActive>
                <label>לא נמצאה תכנית מתאימה</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Website_Request__c.field-meta.xml
<CustomField>
    <fullName>Website_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>בקשה שנפתחה מהאתר</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Child_Request.recordType-meta.xml
<RecordType>
    <fullName>Child_Request</fullName>
    <active>true</active>
    <label>בקשה</label>
</RecordType>

force-app/main/default/objects/Request__c/recordTypes/Parent_Request.recordType-meta.xml
<RecordType>
    <fullName>Parent_Request</fullName>
    <active>true</active>
    <label>בקשה מרכזת</label>
</RecordType>

force-app/main/default/classes/WS_Service_OJT.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-23-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   04-12-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class WS_Service_OJT extends RestClient{
    final static Id parentRequest_RT = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Parent_Request').getRecordTypeId();
    final static Id childRequest_RT = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Child_Request').getRecordTypeId();
    final static Id ojtProgramRequest_RT = Schema.SObjectType.ProgramRequest__c.getRecordTypeInfosByDeveloperName().get('OJT_Recommendation').getRecordTypeId();
    
    public WS_Service_OJT() {
        super(null, null);
    }

    public WS_Service_OJT(RestRequest request, RestResponse response, String objectExtId) {
		super(request,response);
    }
    
    public override object get(){
        return null;
    }

    public override object post(){
        List<Request__c> reqsToInsert = new List<Request__c>();
        List<ProgramRequest__c> progReqsToInsert = new List<ProgramRequest__c>();
        Request__c parentReqToInsert = new Request__c();
        try{
            Map<String, Object> jsonrequest = (Map<String, Object>)JSON.deserializeUntyped(request.requestBody.toString());
            Decimal reqNum = Decimal.valueOf(String.valueOf(jsonrequest.get('professionsCnt')));
            system.debug('///reqNum: ' + reqNum);
            system.debug('///jsonrequest: ' + jsonrequest);
            //if(jsonrequest.get('newValues') instanceOf List<Object>){//If there are more than one element
            if(reqNum > 1){//If there are more than one element
                system.debug('///inside1 ');
                parentReqToInsert = createParentRequest(jsonrequest, (List<Object>)jsonrequest.get('newValues'));
				Database.upsert(parentReqToInsert, Request__c.ExtId__c, false); //Insert the parent's list
                for(Object newReq : (List<Object>)jsonrequest.get('newValues')){
                    reqsToInsert.add(createChildRequest((Map<String, Object>)newReq, parentReqToInsert.Id));
                }
            } else{
                system.debug('///inside2 ');
                //Object newReq = jsonrequest.get('newValues');
                //reqsToInsert.add(createChildRequest((Map<String, Object>)newReq, null));
                for(Object newReq : (List<Object>)jsonrequest.get('newValues')){
                    reqsToInsert.add(createChildRequest((Map<String, Object>)newReq, null));
                }
            }

            //Insert Request Lists + create related Program Request Lists
            if(reqsToInsert.size() > 0){
				Database.upsert(reqsToInsert, Request__c.ExtId__c, false);	
                for(Request__c req : reqsToInsert){
                    progReqsToInsert.add(createProgramRequest(req.Id, req));
                }
            }
            //Insert Program Request Lists
            if(progReqsToInsert.size() > 0){
				Database.upsert(progReqsToInsert, ProgramRequest__c.ExtId__c, false);	
            }

            //Return Request Id
            if(parentReqToInsert.Id != null){//If there are more than one element - return the parent
                return returnId(parentReqToInsert.Id);
            } else if(!reqsToInsert.isEmpty() && reqsToInsert[0].Id != null){
                return returnId(reqsToInsert[0].Id);
            }
        }
        catch(Exception e){
            //Return Error + Request Id
            System.debug('///' + e.getMessage());
            if(parentReqToInsert.Id != null){//If there are more than one element - return the parent
            	return returnErrorId(parentReqToInsert.Id, e.getMessage());
            } else if(!reqsToInsert.isEmpty() && reqsToInsert[0].Id != null){
                return returnErrorId(reqsToInsert[0].Id, e.getMessage());
            }
            return s500();
        }

        return s404();
    }
    
    private Request__c createParentRequest(Map<String, Object> jsonrequest, List<Object> newReqs){
        Object newReq = newReqs != null && newReqs.size() > 0 ? newReqs[0] : null;
        Map<String, Object> newReqMap = (Map<String, Object>)newReq;
        Request__c parentReq = new Request__c();
        parentReq.RecordTypeId = parentRequest_RT;
        parentReq.Request_Status__c = Label_Utils.requestStatus.get('סגור');
        parentReq.JSON__c = Json.serializePretty(jsonrequest);
        parentReq.Program__r = new Program__c(External_Program_Id__c = Label_Utils.programs.get('ojt'));
        parentReq.Request_Details__c = Label.TestUtils_RequestDetails;
        parentReq.ExtId__c = newReqMap.get('RequestNumber') != null ? String.valueOf(newReqMap.get('RequestNumber')).substringBefore('_') : null;
        parentReq.Website_Request__c = true;
        system.debug('///parentReq: ' + parentReq);
        return parentReq;
    }
    
    private Request__c createChildRequest(Map<String, Object> jsonrequest, Id parentId){
        Request__c req = new Request__c();
        req.JSON__c = Json.serializePretty(jsonrequest);
        req.Program__r = new Program__c(External_Program_Id__c = Label_Utils.programs.get('ojt'));
        req.Request_Status__c = Label_Utils.requestStatus.get('סגור');
        req.Request_Number__c = String.valueOf(jsonrequest.get('RequestNumber')).substringBefore('_');
        req.ExtId__c = (String)jsonrequest.get('RequestNumber');
        req.Employees_Requested_Num__c = Decimal.valueOf(String.valueOf(jsonrequest.get('NumofEmployyesInTraining')));
        req.Employees__c = Decimal.valueOf(String.valueOf(jsonrequest.get('NumofEmployyesInTraining')));
        req.Job__c = jsonrequest.get('ProfessionName') != null ? String.valueOf(jsonrequest.get('ProfessionName')).replaceAll('[0-9]', '') : '';
        req.RecordTypeId = childRequest_RT;
        req.Request__c = parentId;
        req.Closing_Reason__c = Label_Utils.reqsClosingReason.get('הועבר לטיפול בתוכנית');
        req.Website_Request__c = true;
        system.debug('///req: ' + req);
        return req;
    }
    
    private ProgramRequest__c createProgramRequest(Id reqId, Request__c req){
        ProgramRequest__c pr = new ProgramRequest__c();
        pr.RecordTypeId = ojtProgramRequest_RT;
        pr.Program__r = new Program__c(External_Program_Id__c = Label_Utils.programs.get('ojt'));
        pr.Status__c = Label_Utils.programRequestStatus.get('הועבר לטיפול המפעיל');
        pr.Request__c = reqId;
        pr.ExtId__c = req.ExtId__c;
        pr.Mail_Employer__c = false;
        pr.API__c = true;
        system.debug('///pr: ' + pr);
        return pr;
    }

}