force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>עתידית</fullName>
            </value>
            <value>
                <fullName>בהקמה</fullName>
            </value>
            <value>
                <fullName>פעילה</fullName>
            </value>
            <value>
                <fullName>מוקפאת</fullName>
            </value>
            <value>
                <fullName>הסתיימה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/ProgramRequest__c.object-meta.xml
<CustomObject>
    <label>תכנית למעסיק</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>ProgramRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>תכניות למעסיק</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramRequest__c/fields/Primary_Contact_PR__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_PR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
            </value>
            <value>
                <fullName>נוצר קשר טלפוני עם המעסיק</fullName>
            </value>
            <value>
                <fullName>קיבל פרטים, שוקל הצטרפות</fullName>
            </value>
            <value>
                <fullName>מילא טפסים- בתהליך הצטרפות</fullName>
            </value>
            <value>
                <fullName>איסוף צרכים מהמעסיק</fullName>
            </value>
            <value>
                <fullName>השלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>נחתם הסכם עם המעסיק</fullName>
            </value>
            <value>
                <fullName>המעסיק הצטרף להכשרה קיימת</fullName>
            </value>
            <value>
                <fullName>גיבוש קבוצת מעסיקים</fullName>
            </value>
            <value>
                <fullName>הושלם תהליך הגיוס</fullName>
            </value>
            <value>
                <fullName>המעסיק לא מעוניין להצטרף</fullName>
            </value>
            <value>
                <fullName>הבקשה נדחתה</fullName>
            </value>
            <value>
                <fullName>אושר</fullName>
            </value>
            <value>
                <fullName>טיפול בערעור</fullName>
            </value>
            <value>
                <fullName>בטיפול המשרד</fullName>
            </value>
            <value>
                <fullName>תקציב נגמר</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים מלאה</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים חלקית</fullName>
            </value>
            <value>
                <fullName>אזל מלאי שוברים</fullName>
            </value>
            <value>
                <fullName>הושלם</fullName>
                <isActive>false</isActive>
                <label>הושלם</label>
            </value>
            <value>
                <fullName>המלצת רכז</fullName>
                <isActive>false</isActive>
                <label>המלצת רכז</label>
            </value>
            <value>
                <fullName>הצטרף לתוכנית</fullName>
                <isActive>false</isActive>
                <label>הצטרף לתוכנית</label>
            </value>
            <value>
                <fullName>לא מתאים</fullName>
                <isActive>false</isActive>
                <label>לא מתאים</label>
            </value>
            <value>
                <fullName>נדחה</fullName>
                <isActive>false</isActive>
                <label>נדחה</label>
            </value>
            <value>
                <fullName>נוצר קשר ע&quot;י התוכנית</fullName>
                <isActive>false</isActive>
                <label>נוצר קשר ע&quot;י התוכנית</label>
            </value>
            <value>
                <fullName>סיים את התוכנית</fullName>
                <isActive>false</isActive>
                <label>סיים את התוכנית</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BATCH_sendEmailVoucherStock.cls
global with sharing class BATCH_sendEmailVoucherStock implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful{

    global BATCH_sendEmailVoucherStock() {
        initData();
    }

    global void initData(){

    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        String queryStr = 'SELECT Id FROM Voucher_Stock__c WHERE Send_Email__c = true';
        return Database.getQueryLocator(queryStr);
    }
    
    global void execute(Database.BatchableContext bc, List<Voucher_Stock__c> sobjs){
        Set<Id> vouStoIds = new Set<Id>();
        for(Voucher_Stock__c vs : sobjs){
            vouStoIds.add(vs.Id);
            vs.Send_Email__c = false;
        }

        System.debug('///vouStoIds: ' + vouStoIds);
        String prStatus = Label_Utils.programRequestStatus.get('אזל מלאי שוברים');
        List<ProgramRequest__c> proReqList = [SELECT Id, Status__c, Primary_Contact_PR__c, Primary_Contact_PR__r.Email FROM ProgramRequest__c 
                                                WHERE Program__r.Name = 'שובר למעסיק' AND Status__c =: prStatus AND Voucher_Stock__c in: vouStoIds
                                                AND CreatedDate = LAST_N_DAYS:180];
        System.debug('///proReqList: ' + proReqList);
        for(ProgramRequest__c pr : proReqList){
            if(pr.Primary_Contact_PR__c != null && pr.Primary_Contact_PR__r.Email != null)
                sendEmailStockUpdated(pr.Primary_Contact_PR__c, pr.Id);
        }

        Database.Update(sobjs, false);
    }

    global void finish(Database.BatchableContext bc){
    }

    public void sendEmailStockUpdated(Id contactId, Id prId){
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE Name = 'עדכון מלאי שוברים' limit 1];
 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setTargetObjectId(contactId);
        mail.setTemplateId(et.id);
        mail.setWhatId(prId);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}