force-app/main/default/objects/ProgramRequest__c/ProgramRequest__c.object-meta.xml
<CustomObject>
    <label>תכנית למעסיק</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>ProgramRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>תכניות למעסיק</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ארגון</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
            </value>
            <value>
                <fullName>נוצר קשר טלפוני עם המעסיק</fullName>
            </value>
            <value>
                <fullName>קיבל פרטים, שוקל הצטרפות</fullName>
            </value>
            <value>
                <fullName>מילא טפסים- בתהליך הצטרפות</fullName>
            </value>
            <value>
                <fullName>איסוף צרכים מהמעסיק</fullName>
            </value>
            <value>
                <fullName>השלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>נחתם הסכם עם המעסיק</fullName>
            </value>
            <value>
                <fullName>המעסיק הצטרף להכשרה קיימת</fullName>
            </value>
            <value>
                <fullName>גיבוש קבוצת מעסיקים</fullName>
            </value>
            <value>
                <fullName>הושלם תהליך הגיוס</fullName>
            </value>
            <value>
                <fullName>המעסיק לא מעוניין להצטרף</fullName>
            </value>
            <value>
                <fullName>הבקשה נדחתה</fullName>
            </value>
            <value>
                <fullName>אושר</fullName>
            </value>
            <value>
                <fullName>טיפול בערעור</fullName>
            </value>
            <value>
                <fullName>בטיפול המשרד</fullName>
            </value>
            <value>
                <fullName>תקציב נגמר</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים מלאה</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים חלקית</fullName>
            </value>
            <value>
                <fullName>אזל מלאי שוברים</fullName>
            </value>
            <value>
                <fullName>הושלם</fullName>
                <isActive>false</isActive>
                <label>הושלם</label>
            </value>
            <value>
                <fullName>המלצת רכז</fullName>
                <isActive>false</isActive>
                <label>המלצת רכז</label>
            </value>
            <value>
                <fullName>הצטרף לתוכנית</fullName>
                <isActive>false</isActive>
                <label>הצטרף לתוכנית</label>
            </value>
            <value>
                <fullName>לא מתאים</fullName>
                <isActive>false</isActive>
                <label>לא מתאים</label>
            </value>
            <value>
                <fullName>נדחה</fullName>
                <isActive>false</isActive>
                <label>נדחה</label>
            </value>
            <value>
                <fullName>נוצר קשר ע&quot;י התוכנית</fullName>
                <isActive>false</isActive>
                <label>נוצר קשר ע&quot;י התוכנית</label>
            </value>
            <value>
                <fullName>סיים את התוכנית</fullName>
                <isActive>false</isActive>
                <label>סיים את התוכנית</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/vouchers_approved__c.field-meta.xml
<CustomField>
    <fullName>vouchers_approved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>כמות שוברים מאושרת להקצאה</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>שובר</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>מספר שובר</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>שוברים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>שובר פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/ProgramRequest__c.field-meta.xml
<CustomField>
    <fullName>ProgramRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>תוכנית למעסיק</label>
    <referenceTo>ProgramRequest__c</referenceTo>
    <relationshipLabel>שוברים</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Rejected_Date__c.field-meta.xml
<CustomField>
    <fullName>Rejected_Date__c</fullName>
    <description>תאריך בו השובר הפך לפג תוקף</description>
    <label>Rejected Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>מצב שובר</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>אושר עקרונית וממתין לגיוס עובד</fullName>
                <default>true</default>
                <label>אושר עקרונית וממתין לגיוס עובד</label>
            </value>
            <value>
                <fullName>בדיקת העובד שהוגש ע&quot;י החברה המנהלת</fullName>
            </value>
            <value>
                <fullName>ממתין להשלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>גויס עובד</fullName>
            </value>
            <value>
                <fullName>מומש חלקית</fullName>
            </value>
            <value>
                <fullName>מומש במלואו</fullName>
            </value>
            <value>
                <fullName>הליך ערעור- ממתין לקבלת ערעור מהמעסיק</fullName>
            </value>
            <value>
                <fullName>הליך ערעור- ממתין להחלטת המשרד</fullName>
            </value>
            <value>
                <fullName>נדחה- פג תוקף</fullName>
            </value>
            <value>
                <fullName>נדחה- לא אושר עובד</fullName>
            </value>
            <value>
                <fullName>נדחה וממתין להודעה בדבר הגשת ערעור</fullName>
                <isActive>false</isActive>
                <label>נדחה וממתין להודעה בדבר הגשת ערעור</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>שוברים</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProgramRequestHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-30-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ProgramRequestHandler extends TriggerHandler{
    
    public override void beforeUpdate(){
        beforeUpdateGetSuitableRecord(Trigger.new, Trigger.oldMap);
    }

    //-----------------------------Before Update--------------------------------
    private void beforeUpdateGetSuitableRecord(List<ProgramRequest__c> newRequest, Map<Id, SObject> oldMapRequest){
        Map<String, List<ProgramRequest__c>> accHpProReqMap = new Map<String, List<ProgramRequest__c>>();
        Map<String, Decimal> accHpVouchNumMap = new Map<String, Decimal>();
        for(ProgramRequest__c pr : newRequest){
            ProgramRequest__c oldProRequest = (ProgramRequest__c)oldMapRequest.get(pr.Id);
            if((pr.vouchers_approved__c != null && pr.vouchers_approved__c != oldProRequest.vouchers_approved__c && pr.vouchers_approved__c > oldProRequest.vouchers_approved__c)){//Need to create vouchers
                if(pr.Status__c == Label_Utils.programRequestStatus.get('הקצאת שוברים חלקית') || pr.Status__c == Label_Utils.programRequestStatus.get('הקצאת שוברים מלאה')){
                    Decimal numVouchers = oldProRequest.vouchers_approved__c != null ? pr.vouchers_approved__c - oldProRequest.vouchers_approved__c : pr.vouchers_approved__c;
                    if(!accHpProReqMap.containsKey(pr.Account__c))
                        accHpProReqMap.put(pr.Account__c, new List<ProgramRequest__c>());
                    accHpProReqMap.get(pr.Account__c).add(pr);
                    
                    if(!accHpVouchNumMap.containsKey(pr.Account__c))
                        accHpVouchNumMap.put(pr.Account__c, 0);
                    accHpVouchNumMap.put(pr.Account__c, accHpVouchNumMap.get(pr.Account__c) + numVouchers);
                } else{
                    //pr.addError(Label.AddError_noRightStatus);
                }
            }
        }

        if(accHpVouchNumMap.keySet().Size() > 0)
            checkVoucherCreation(accHpVouchNumMap, accHpProReqMap, oldMapRequest);
    }
    
    private void checkVoucherCreation(Map<String, Decimal> accHpVouchNumMap, Map<String, List<ProgramRequest__c>> accHpProReqMap, Map<Id, SObject> oldMapRequest){
        //Get all active Vouchers per Account in the current year
        Map<String, Decimal> accHpAllocVouchNumMap = new Map<String, Decimal>();
        Map<String, Decimal> accHpAllocRejectedVouchNumMap = new Map<String, Decimal>();
        Integer currentYear = Date.Today().Year();
        List<Voucher__c> vouchs = [SELECT Id, ProgramRequest__r.Account__c, Active__c, Status__c, Rejected_Date__c, CreatedDate
                                    FROM Voucher__c
                                   	WHERE ProgramRequest__r.Account__c in: accHpVouchNumMap.keySet()];
        System.debug('///vouchs: ' + vouchs);
        
        //Add new request Vouchers to the Vouchers that have already been allocated in the last year
        for(Voucher__c vc : vouchs){
            if(vc.Active__c == True && currentYear == vc.CreatedDate.year()){
                if(!accHpAllocVouchNumMap.containsKey(vc.ProgramRequest__r.Account__c))
                    accHpAllocVouchNumMap.put(vc.ProgramRequest__r.Account__c, 0);
                accHpAllocVouchNumMap.put(vc.ProgramRequest__r.Account__c, accHpAllocVouchNumMap.get(vc.ProgramRequest__r.Account__c) + 1);
            }
            //Map rejected vouchers per Account
            if(vc.Status__c == Label_Utils.voucherStatus.get('נדחה- פג תוקף') && vc.Rejected_Date__c != null && currentYear == vc.Rejected_Date__c.year()){
                if(!accHpAllocRejectedVouchNumMap.containsKey(vc.ProgramRequest__r.Account__c))
                    accHpAllocRejectedVouchNumMap.put(vc.ProgramRequest__r.Account__c, 0);
                accHpAllocRejectedVouchNumMap.put(vc.ProgramRequest__r.Account__c, accHpAllocRejectedVouchNumMap.get(vc.ProgramRequest__r.Account__c) + 1);
            }
        }

        System.debug('///accHpAllocVouchNumMap: ' + accHpAllocVouchNumMap);
        System.debug('///accHpAllocRejectedVouchNumMap: ' + accHpAllocRejectedVouchNumMap);
        List<Voucher__c> newVchsList = getVouchersToCreate(accHpVouchNumMap, accHpProReqMap, accHpAllocVouchNumMap, oldMapRequest, accHpAllocRejectedVouchNumMap);
        System.debug('///newVchsList: ' + newVchsList);
        if(newVchsList.size() > 0){
            Database.insert(newVchsList, true);
        }
    }

    private List<Voucher__c> getVouchersToCreate(Map<String, Decimal> accHpVouchNumMap, Map<String, List<ProgramRequest__c>> accHpProReqMap, Map<String, Decimal> accHpAllocVouchNumMap, Map<Id, SObject> oldMapRequest, Map<String, Decimal> accHpAllocRejectedVouchNumMap){
        List<Voucher__c> newVchsList = new List<Voucher__c>();
        System.debug('///accHpVouchNumMap: ' + accHpVouchNumMap);
        for(String hp : accHpVouchNumMap.keySet()){
            List<ProgramRequest__c> prs = accHpProReqMap.get(hp);
            Decimal sumNumVouchs = accHpAllocVouchNumMap.get(hp) != null ? accHpVouchNumMap.get(hp) + accHpAllocVouchNumMap.get(hp) :  accHpVouchNumMap.get(hp);
            if(sumNumVouchs > 10 && !Test.isRunningTest()){//If more than 10
                for(ProgramRequest__c pr : prs){
                    pr.addError(Label.AddError_noMoreThan10Vouchers + ': ' + (accHpAllocVouchNumMap.get(hp) != null ? accHpAllocVouchNumMap.get(hp) : 0));
                }
            } 
            if(accHpAllocRejectedVouchNumMap.get(hp) >= 15 && !Test.isRunningTest()){//If have more or equal than 15 rejected vouchers
                for(ProgramRequest__c pr : prs){
                    pr.addError(Label.AddError_noMoreThan15RejectedVouchers);
                }
            } else{//Create requested Vouchers
                for(ProgramRequest__c pr : prs){
                    ProgramRequest__c oldProRequest = (ProgramRequest__c)oldMapRequest.get(pr.Id);
                    Decimal numVouchers = oldProRequest.vouchers_approved__c != null && pr.vouchers_approved__c > oldProRequest.vouchers_approved__c ? pr.vouchers_approved__c - oldProRequest.vouchers_approved__c : pr.vouchers_approved__c;
                    for(Integer i = 0; i < numVouchers; i++){
                        newVchsList.add(createVoucher(pr));
                    }
                }
            }
        }
        return newVchsList;
    }
    
    private Voucher__c createVoucher(ProgramRequest__c pr){
        Voucher__c vc = new Voucher__c();
        vc.Active__c = true;
        vc.ProgramRequest__c = pr.Id;
        vc.Voucher_Stock__c = pr.Voucher_Stock__c;
        vc.Status__c = Label_Utils.voucherStatus.get('אושר עקרונית וממתין לגיוס עובד');
        return vc;
    }
    

}