force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>עיר</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ערים</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>עתידית</fullName>
            </value>
            <value>
                <fullName>בהקמה</fullName>
            </value>
            <value>
                <fullName>פעילה</fullName>
            </value>
            <value>
                <fullName>מוקפאת</fullName>
            </value>
            <value>
                <fullName>הסתיימה</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/ProgramRequest__c.object-meta.xml
<CustomObject>
    <label>תכנית למעסיק</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>ProgramRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>תכניות למעסיק</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProgramRequest__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ארגון</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Primary_Contact_PR__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_PR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Qty_vouchers_requested__c.field-meta.xml
<CustomField>
    <fullName>Qty_vouchers_requested__c</fullName>
    <label>כמות שוברים מבוקשת</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>ProgramRequests</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>הועבר למילוי טפסים</fullName>
            </value>
            <value>
                <fullName>הועבר לטיפול המפעיל</fullName>
            </value>
            <value>
                <fullName>נוצר קשר טלפוני עם המעסיק</fullName>
            </value>
            <value>
                <fullName>קיבל פרטים, שוקל הצטרפות</fullName>
            </value>
            <value>
                <fullName>מילא טפסים- בתהליך הצטרפות</fullName>
            </value>
            <value>
                <fullName>איסוף צרכים מהמעסיק</fullName>
            </value>
            <value>
                <fullName>השלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>נחתם הסכם עם המעסיק</fullName>
            </value>
            <value>
                <fullName>המעסיק הצטרף להכשרה קיימת</fullName>
            </value>
            <value>
                <fullName>גיבוש קבוצת מעסיקים</fullName>
            </value>
            <value>
                <fullName>הושלם תהליך הגיוס</fullName>
            </value>
            <value>
                <fullName>המעסיק לא מעוניין להצטרף</fullName>
            </value>
            <value>
                <fullName>הבקשה נדחתה</fullName>
            </value>
            <value>
                <fullName>אושר</fullName>
            </value>
            <value>
                <fullName>טיפול בערעור</fullName>
            </value>
            <value>
                <fullName>בטיפול המשרד</fullName>
            </value>
            <value>
                <fullName>תקציב נגמר</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים מלאה</fullName>
            </value>
            <value>
                <fullName>הקצאת שוברים חלקית</fullName>
            </value>
            <value>
                <fullName>אזל מלאי שוברים</fullName>
            </value>
            <value>
                <fullName>הושלם</fullName>
                <isActive>false</isActive>
                <label>הושלם</label>
            </value>
            <value>
                <fullName>המלצת רכז</fullName>
                <isActive>false</isActive>
                <label>המלצת רכז</label>
            </value>
            <value>
                <fullName>הצטרף לתוכנית</fullName>
                <isActive>false</isActive>
                <label>הצטרף לתוכנית</label>
            </value>
            <value>
                <fullName>לא מתאים</fullName>
                <isActive>false</isActive>
                <label>לא מתאים</label>
            </value>
            <value>
                <fullName>נדחה</fullName>
                <isActive>false</isActive>
                <label>נדחה</label>
            </value>
            <value>
                <fullName>נוצר קשר ע&quot;י התוכנית</fullName>
                <isActive>false</isActive>
                <label>נוצר קשר ע&quot;י התוכנית</label>
            </value>
            <value>
                <fullName>סיים את התוכנית</fullName>
                <isActive>false</isActive>
                <label>סיים את התוכנית</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>תוכניות למעסיק</relationshipLabel>
    <relationshipName>ProgramRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/fields/vouchers_approved__c.field-meta.xml
<CustomField>
    <fullName>vouchers_approved__c</fullName>
    <defaultValue>0</defaultValue>
    <label>כמות שוברים מאושרת להקצאה</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProgramRequest__c/recordTypes/Shovar_Lamaasik.recordType-meta.xml
<RecordType>
    <fullName>Shovar_Lamaasik</fullName>
    <active>true</active>
    <label>שובר למעסיק</label>
</RecordType>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if there is only one, when the programrequest is created then also this lookup to program is filled</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>שובר</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>מספר שובר</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>שוברים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>שובר פעיל</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/ProgramRequest__c.field-meta.xml
<CustomField>
    <fullName>ProgramRequest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>תוכנית למעסיק</label>
    <referenceTo>ProgramRequest__c</referenceTo>
    <relationshipLabel>שוברים</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>מצב שובר</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>אושר עקרונית וממתין לגיוס עובד</fullName>
                <default>true</default>
                <label>אושר עקרונית וממתין לגיוס עובד</label>
            </value>
            <value>
                <fullName>בדיקת העובד שהוגש ע&quot;י החברה המנהלת</fullName>
            </value>
            <value>
                <fullName>ממתין להשלמת מסמכים</fullName>
            </value>
            <value>
                <fullName>גויס עובד</fullName>
            </value>
            <value>
                <fullName>מומש חלקית</fullName>
            </value>
            <value>
                <fullName>מומש במלואו</fullName>
            </value>
            <value>
                <fullName>הליך ערעור- ממתין לקבלת ערעור מהמעסיק</fullName>
            </value>
            <value>
                <fullName>הליך ערעור- ממתין להחלטת המשרד</fullName>
            </value>
            <value>
                <fullName>נדחה- פג תוקף</fullName>
            </value>
            <value>
                <fullName>נדחה- לא אושר עובד</fullName>
            </value>
            <value>
                <fullName>נדחה וממתין להודעה בדבר הגשת ערעור</fullName>
                <isActive>false</isActive>
                <label>נדחה וממתין להודעה בדבר הגשת ערעור</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Voucher__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>שוברים</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher_Stock__c/fields/Qty_vouchers_requested__c.field-meta.xml
<CustomField>
    <fullName>Qty_vouchers_requested__c</fullName>
    <label>כמות שוברים שהוקצו</label>
    <summaryFilterItems>
        <field>Voucher__c.Active__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Voucher__c.Voucher_Stock__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ProgramRequestHandler_Test.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-17-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class ProgramRequestHandler_Test {
    @isTest
    static void requestTest(){    

        List<ProgramRequest__c> proReqsList = [SELECT Id, vouchers_approved__c FROM ProgramRequest__c Limit 1];
        Test.startTest();
        proReqsList[0].vouchers_approved__c = 4;
        update proReqsList;
        Test.stopTest();
    }

    @TestSetup
    static void makeData(){
        List<City__c> cityList = TEST_Utils.createTestCity(new List<City__c>{new City__c()});
        insert cityList;
        
        Account acc = TEST_Utils.createTestAccount(new List<Account>{new Account()})[0];
        insert acc;

        Contact con = TEST_Utils.createTestContact(new List<Contact>{new Contact(AccountId = acc.Id)})[0];
        insert con;
        
        Program__c pro = TEST_Utils.createTestProgram(new List<Program__c>{new Program__c()})[0];
        insert pro;
        
        Request__c childRequest = TEST_Utils.createTestChildRequest(new List<Request__c>{new Request__c(Account__c = acc.Id, Primary_Contact__c = con.Id, Program__c = pro.Id)})[0];
        insert childRequest;
        
        List<Voucher_Stock__c> vouchStockList = TEST_Utils.createTestVoucherStock(new List<Voucher_Stock__c>{new Voucher_Stock__c()});
        insert vouchStockList;

        Id proReqShovar_RT = Schema.SObjectType.ProgramRequest__c.getRecordTypeInfosByDeveloperName().get('Shovar_Lamaasik').getRecordTypeId();
        List<ProgramRequest__c> proReqsList = TEST_Utils.createTestProgramRequest(new List<ProgramRequest__c>{new ProgramRequest__c(RecordTypeId = proReqShovar_RT, Account__c = acc.Id, Primary_Contact_PR__c = con.Id, Request__c = childRequest.Id, Program__c = pro.Id, Voucher_Stock__c = vouchStockList[0].Id, Qty_vouchers_requested__c = 5, vouchers_approved__c = 0, Status__c = Label_Utils.programRequestStatus.get('הקצאת שוברים חלקית'))});
        insert proReqsList;

        List<Voucher__c> vouchList = TEST_Utils.createTestVoucher(new List<Voucher__c>{new Voucher__c(Voucher_Stock__c = vouchStockList[0].Id, ProgramRequest__c = proReqsList[0].Id, Active__c = true),
                                                                                        new Voucher__c(Voucher_Stock__c = vouchStockList[0].Id, ProgramRequest__c = proReqsList[0].Id, Status__c = Label_Utils.voucherStatus.get('נדחה- פג תוקף'))});
        insert vouchList;
    }
}