force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ארגון</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/contact_from_request__c.field-meta.xml
<CustomField>
    <fullName>contact_from_request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>נא לשייך את איש הקשר מהבקשה לסניף זה</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>סניפים</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>סניף/מקום עבודה</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>יחידה אחראית</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.Account__r.Name</field>
            <operation>equals</operation>
            <value>זרוע העבודה</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Date_Close_Request__c.field-meta.xml
<CustomField>
    <fullName>Date_Close_Request__c</fullName>
    <label>תאריך סגירת בקשה</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Date_Closing__c.field-meta.xml
<CustomField>
    <fullName>Date_Closing__c</fullName>
    <label>תאריך בקשה סגורה</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Date_Complete_Info__c.field-meta.xml
<CustomField>
    <fullName>Date_Complete_Info__c</fullName>
    <label>תאריך השלמת פרטים</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Date_Needs_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Date_Needs_Mapping__c</fullName>
    <label>תאריך מיפוי צרכים</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Date_Program_Request__c.field-meta.xml
<CustomField>
    <fullName>Date_Program_Request__c</fullName>
    <label>תאריך המלצה לתוכנית</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Field1__c.field-meta.xml
<CustomField>
    <fullName>Field1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>האם מקושר לבקשת אב</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>if there is only one, when the programrequest is created then also this lookup to program is filled</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Details__c.field-meta.xml
<CustomField>
    <fullName>Request_Details__c</fullName>
    <label>Request Details</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>Complete_Info</fullName>
                <label>השלמת פרטים</label>
            </value>
            <value>
                <fullName>Needs_mapping</fullName>
                <label>מיפוי צרכים</label>
            </value>
            <value>
                <fullName>programRequest</fullName>
                <label>המלצה לתכנית</label>
            </value>
            <value>
                <fullName>CloseRequest</fullName>
                <label>סגירת בקשה</label>
            </value>
            <value>
                <fullName>סגור</fullName>
            </value>
            <value>
                <fullName>לא נמצאה תכנית מתאימה</fullName>
                <isActive>false</isActive>
                <label>לא נמצאה תכנית מתאימה</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Submition_Id__c.field-meta.xml
<CustomField>
    <fullName>Submition_Id__c</fullName>
    <label>Submition Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Website_Request__c.field-meta.xml
<CustomField>
    <fullName>Website_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>בקשה שנפתחה מהאתר</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Child_Request.recordType-meta.xml
<RecordType>
    <fullName>Child_Request</fullName>
    <active>true</active>
    <label>בקשה</label>
</RecordType>

force-app/main/default/objects/Request__c/recordTypes/Parent_Request.recordType-meta.xml
<RecordType>
    <fullName>Parent_Request</fullName>
    <active>true</active>
    <label>בקשה מרכזת</label>
</RecordType>

force-app/main/default/globalValueSets/District.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>National</fullName>
        <label>כל הארץ</label>
    </customValue>
    <customValue>
        <fullName>North</fullName>
        <label>צפון</label>
    </customValue>
    <customValue>
        <fullName>Center</fullName>
        <label>מרכז</label>
    </customValue>
    <customValue>
        <fullName>Jerusalem</fullName>
        <label>ירושלים</label>
    </customValue>
    <customValue>
        <fullName>South</fullName>
        <label>דרום</label>
    </customValue>
    <customValue>
        <fullName>Eilat</fullName>
        <label>אילת</label>
    </customValue>
    <masterLabel>District</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RequestHandler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-06-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   03-17-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class RequestHandler extends TriggerHandler{
    
    final static Id parentRequest_RT = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Parent_Request').getRecordTypeId();
    final static Id childRequest_RT = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Child_Request').getRecordTypeId();

    public override void afterInsert(){
        checkCreatingParentRequest(Trigger.new);
    }

    public override void beforeUpdate(){
        beforeUpdateGetSuitableRecord(Trigger.new, Trigger.oldMap);
    }

    //-----------------------------Before Update--------------------------------
    private void beforeUpdateGetSuitableRecord(List<Request__c> newRequest, Map<Id, SObject> oldMapRequest){
        Map<Id, Request__c> branchContactMap = new Map<Id, Request__c>();
        Map<String, Request__c> accConRequestMap = new Map<String, Request__c>();
        Map<Id, Request__c> parentReqOwnerChanged = new Map<Id, Request__c>();
        Map<Id, List<Request__c>> parentChildsRequest = new Map<Id, List<Request__c>>();
        Set<Id> requestId = new Set<Id>();

        for(Request__c rq : newRequest){
            Request__c oldRequest = (Request__c)oldMapRequest.get(rq.Id);
            System.debug('///rq: ' + rq);
            System.debug('///oldRequest: ' + oldRequest);
            if((rq.Request_Status__c != oldRequest.Request_Status__c)){//If status changed
                updateDateStatusFields(rq, oldRequest);
            }
            if((rq.Branch__c != null && oldRequest.Branch__c == null)){//If branch was populated
                branchContactMap.put(rq.Branch__c, rq);
                accConRequestMap.put('' + rq.Account__c + rq.Primary_Contact__c, rq);
            }
            if(rq.RecordTypeId == parentRequest_RT && oldRequest.OwnerId != rq.OwnerId){//If owner changed
                parentReqOwnerChanged.put(rq.Id, rq);
            }
            if(rq.RecordTypeId == childRequest_RT && oldRequest.Request_Status__c != rq.Request_Status__c){//If status changed
                requestId.add(rq.Id);
                if(!parentChildsRequest.containsKey(rq.Request__c))
                    parentChildsRequest.put(rq.Request__c, new List<Request__c>());
                parentChildsRequest.get(rq.Request__c).add(rq);
            }
        }

        if(branchContactMap.size() > 0 || accConRequestMap.size() > 0){
            updateBranchWithContact(branchContactMap, accConRequestMap);
        }
        if(parentChildsRequest.size() > 0){ 
            updateParentStatus(requestId, parentChildsRequest); 
        }
        if(parentReqOwnerChanged.size() > 0){
            updateChildsOwner(parentReqOwnerChanged); 
        }
    }

    //------------Update date status fields-------------
    private void updateDateStatusFields(Request__c rq, Request__c oldRequest){
        System.debug('///rq: ' + rq);
        if(rq.Request_Status__c == Label_Utils.requestStatus.get('השלמת פרטים')){
            rq.Date_Complete_Info__c = datetime.now();
        } else if(rq.Request_Status__c == Label_Utils.requestStatus.get('מיפוי צרכים')){
            rq.Date_Needs_Mapping__c = datetime.now();
        } else if(rq.Request_Status__c == Label_Utils.requestStatus.get('המלצה לתכנית')){
            rq.Date_Program_Request__c = datetime.now();
        } else if(rq.Request_Status__c == Label_Utils.requestStatus.get('סגירת בקשה')){
            rq.Date_Close_Request__c = datetime.now();
        } else if(rq.Request_Status__c == Label_Utils.requestStatus.get('סגור')){
            rq.Date_Closing__c = datetime.now();
        }
        System.debug('///after: ' + rq);
    }

    //------------After the user insert a new related branch, need to update branch with contact request-------------------
    private void updateBranchWithContact(Map<Id, Request__c> branchContactMap, Map<String, Request__c> accConRequestMap){
        List<Branch__c> branchToUpdate = new List<Branch__c>();
        Map<String, Branch__c> accConBranchMap = new Map<String, Branch__c>();
        Set<Id> primConIds = new Set<Id>();
        Set<Id> accIds = new Set<Id>();
        Set<String> branchNames = new Set<String>();

        getBranchToUpdate(primConIds, accIds, branchNames, accConBranchMap, branchContactMap, branchToUpdate);
        checkBranchCreation(primConIds, accIds, branchNames, accConBranchMap, branchContactMap, accConRequestMap);
        
        if(accConBranchMap.values().size() > 0){
            System.debug('///accConBranchMap.values(): ' + accConBranchMap.values());
            Database.update(accConBranchMap.values(), false);
        }
    }

    //Get branche data related to request
    private void getBranchToUpdate(Set<Id> primConIds, Set<Id> accIds, Set<String> branchNames, Map<String, Branch__c> accConBranchMap, Map<Id, Request__c> branchContactMap, List<Branch__c> branchToUpdate){
        branchToUpdate = [SELECT Id, Primary_Contact__c, Account__c, contact_from_request__c, Name
                            FROM Branch__c 
                            WHERE Id in: branchContactMap.keySet()];

        for(Branch__c br : branchToUpdate){
            if(br.contact_from_request__c == true && br.Primary_Contact__c == null){
                br.Primary_Contact__c = branchContactMap.get(br.Id) != null ? branchContactMap.get(br.Id).Primary_Contact__c : null;
            }
            br.Account__c = branchContactMap.get(br.Id) != null ? branchContactMap.get(br.Id).Account__c : null;
            primConIds.add(br.Primary_Contact__c);
            accIds.add(br.Account__c);
            branchNames.add(br.Name);
            accConBranchMap.put('' + br.Account__c + br.Primary_Contact__c + br.Name, br);
        }
        System.debug('///branchToUpdate: ' + branchToUpdate);
        System.debug('///primConIds: ' + primConIds);
        System.debug('///accIds: ' + accIds);
        System.debug('///branchNames: ' + branchNames);
        System.debug('///accConBranchMap: ' + accConBranchMap);
    }

    //Check duplicate branches in org, if found delete it.
    private void checkBranchCreation(Set<Id> primConIds, Set<Id> accIds, Set<String> branchNames, Map<String, Branch__c> accConBranchMap, Map<Id, Request__c> branchContactMap, Map<String, Request__c> accConRequestMap){
        List<Branch__c> brToDelete = new List<Branch__c>();
        List<Branch__c> duplicateBranch = [SELECT Id, Primary_Contact__c, Account__c, contact_from_request__c, Name
                                            FROM Branch__c 
                                            WHERE Primary_Contact__c in: primConIds AND Account__c in: accIds AND Name in: branchNames AND Id not in: branchContactMap.keySet()];
        System.debug('///accConBranchMap: ' + accConBranchMap);
        System.debug('///duplicateBranch: ' + duplicateBranch);
        for(Branch__c br : duplicateBranch){
            System.debug('///br: ' + br);
            if(accConBranchMap.containsKey('' + br.Account__c + br.Primary_Contact__c + br.Name)){
                brToDelete.add(accConBranchMap.get('' + br.Account__c + br.Primary_Contact__c + br.Name));
                accConBranchMap.remove('' + br.Account__c + br.Primary_Contact__c + br.Name);
                Request__c rq = accConRequestMap.get('' + br.Account__c + br.Primary_Contact__c);
                System.debug('///rq: ' + rq);
                if(rq != null && !Test.isRunningTest())
                    rq.addError(Label.AddError_DuplicateBranch);
            }
        }

        System.debug('///brToDelete: ' + brToDelete);
        System.debug('///accConBranchMap: ' + accConBranchMap);
        if(brToDelete.size() > 0 && !Test.isRunningTest()){
            Database.delete(brToDelete, false);
        }
    }

    //--------------When child request status changed => need to update parent status with the earlier status.
    private void updateParentStatus(Set<Id> requestId, Map<Id, List<Request__c>> parentChildsRequest){
        Map<Id, Request__c> parentRequestMap = getParentRequest(parentChildsRequest.keySet());                
        List<Request__c> reqToUpdate = new List<Request__c>();
        getSiblingRequest(requestId, parentChildsRequest);

        for(Id parId : parentChildsRequest.keySet()){
            Request__c parent = parentRequestMap.get(parId);
            if(parentChildsRequest.get(parId) != null && parent != null){                
                String firstStatus = checkStatus(parentChildsRequest.get(parId));
                parent.Request_Status__c = firstStatus;
                reqToUpdate.add(parent);
            }
        }
        if(reqToUpdate.size() > 0){
            String jsonString = json.serialize(reqToUpdate);
        	updateParentRequest(jsonString);
        }
    }
    
    //Future method because of recosive process builder
    @future
    private static void updateParentRequest(String jsonString){
        List<Request__c> reqToUpdate = (List<Request__c>)Json.deserialize(jsonString, List<Request__c>.class);        
        Database.update(reqToUpdate, false);
    }

    //Get sibling request - have the same parent
    private void getSiblingRequest(Set<Id> requestId, Map<Id, List<Request__c>> parentChildsRequest){
        List<Request__c> siblingRequest = [SELECT Id, Request__c, Request_Status__c 
                                            FROM Request__c 
                                            WHERE Id not in: requestId AND Request__c in: parentChildsRequest.keySet() and RecordTypeId =: childRequest_RT];
        for(Request__c rq : siblingRequest){
            if(!parentChildsRequest.containsKey(rq.Request__c))
                parentChildsRequest.put(rq.Request__c, new List<Request__c>());
            parentChildsRequest.get(rq.Request__c).add(rq);
        }
    }
    
    //Get Parent data
    private Map<Id, Request__c> getParentRequest(Set<Id> parentId){
        List<Request__c> parentRequest = [SELECT Id, Request_Status__c  
                                            FROM Request__c 
                                            WHERE Id in: parentId and RecordTypeId =: parentRequest_RT];
        Map<Id, Request__c> parentRequestMap = new Map<Id, Request__c>();
        for(Request__c rq : parentRequest){
            parentRequestMap.put(rq.Id, rq);
        }
        return parentRequestMap;
    }
    
    //Get the earlier status of all related child request
    private static String checkStatus(List<Request__c> childs){
        String firstStatus;
        for(Request__c rq : childs){
            System.debug('///rq.Request_Status__c: ' + rq.Request_Status__c);
            if(firstStatus == null){
                firstStatus = rq.Request_Status__c;
            } else if(firstStatus == Label_Utils.requestStatus.get('סגור') && rq.Request_Status__c != Label_Utils.requestStatus.get('סגור')){
                firstStatus = rq.Request_Status__c;
            } else if(firstStatus == Label_Utils.requestStatus.get('סגירת בקשה') && (rq.Request_Status__c == Label_Utils.requestStatus.get('המלצה לתכנית') || rq.Request_Status__c == Label_Utils.requestStatus.get('מיפוי צרכים') || rq.Request_Status__c == Label_Utils.requestStatus.get('השלמת פרטים') || rq.Request_Status__c == Label_Utils.requestStatus.get('חדש'))){
                firstStatus = rq.Request_Status__c;
            } else if(firstStatus == Label_Utils.requestStatus.get('המלצה לתכנית') && (rq.Request_Status__c == Label_Utils.requestStatus.get('מיפוי צרכים') || rq.Request_Status__c == Label_Utils.requestStatus.get('השלמת פרטים') || rq.Request_Status__c == Label_Utils.requestStatus.get('חדש'))){
                firstStatus = rq.Request_Status__c;
            } else if(firstStatus == Label_Utils.requestStatus.get('מיפוי צרכים') && (rq.Request_Status__c == Label_Utils.requestStatus.get('השלמת פרטים') || rq.Request_Status__c == Label_Utils.requestStatus.get('חדש'))){
                firstStatus = rq.Request_Status__c;
            } else if(firstStatus == Label_Utils.requestStatus.get('השלמת פרטים') && rq.Request_Status__c == Label_Utils.requestStatus.get('חדש')){
                firstStatus = rq.Request_Status__c;
            }
            System.debug('///firstStatus: ' + firstStatus);
        }
        return firstStatus;
    }
    
    //------------------When parent request owner changed => need to update child's owner-----------------------
    private void updateChildsOwner(Map<Id, Request__c> parentReqOwnerChanged){
        List<Request__c> childRequest = [SELECT Id, Request__c, OwnerId 
                                            FROM Request__c 
                                            WHERE Request__c in: parentReqOwnerChanged.keySet() and RecordTypeId =: childRequest_RT];        
        for(Request__c rq : childRequest){
            if(parentReqOwnerChanged.get(rq.Request__c) != null){
                rq.OwnerId = parentReqOwnerChanged.get(rq.Request__c).OwnerId;
            }
		}        
        if(childRequest.size() > 0){
            Database.update(childRequest, false);
        }
    }
    
    //-----------------------------After insert---------------------------
    //-------------------------Check if there are more than one child with the same Titan submition id, if yes, create a parent request-----------------------
    private void checkCreatingParentRequest(List<Request__c> newRequest){
        Map<String, List<Request__c>> submitionIdRequestsMap = new Map<String, List<Request__c>>(); 
        List<String> submitionIds = new List<String>();
        Set<Id> reqIds = new Set<Id>();

        for(Request__c rq : newRequest){
            if(rq.Submition_Id__c != null && rq.RecordTypeId == childRequest_RT){
                if(!submitionIdRequestsMap.containsKey(rq.Submition_Id__c))
                    submitionIdRequestsMap.put(rq.Submition_Id__c, new List<Request__c>());
                submitionIdRequestsMap.get(rq.Submition_Id__c).add(rq);
                submitionIds.add(rq.Submition_Id__c);
                reqIds.add(rq.Id);
            }
        }
        getSubmitionIdsMap(submitionIds, submitionIdRequestsMap, reqIds);
        if(submitionIdRequestsMap.size() > 0){
            Map<String, Request__c> parentChildRequestsMap = createParentRequest(submitionIdRequestsMap);             
            if(parentChildRequestsMap.size() > 0){
                List<Request__c> requestToUpdate = updateRelatedChilds(parentChildRequestsMap, submitionIdRequestsMap);                
                Database.update(requestToUpdate, false);
            }
        }

    }

    //Check if need to create parent, if yes, create it
    private Map<String, Request__c> createParentRequest(Map<String, List<Request__c>> submitionIdRequestsMap){
        Map<String, Request__c> parentChildRequestsMap = new Map<String, Request__c>();
        List<Request__c> reqToInsert = new List<Request__c>();
        for(String subId : submitionIdRequestsMap.keySet()){
            Decimal numReq = submitionIdRequestsMap.get(subId).size();            
            if(numReq > 1){//More than one child => create parent
                Request__c childReq = submitionIdRequestsMap.get(subId)[0];
                Request__c parentReq = createParent(childReq);                
                reqToInsert.add(parentReq);
                parentChildRequestsMap.put(parentReq.Submition_Id__c, parentReq);
            } else{//If not check if already exist
                Request__c parentReq = checkParentAlreadyExist(subId);                
                if(parentReq != null){
                	parentChildRequestsMap.put(parentReq.Submition_Id__c, parentReq);
                }
            }
        }        
        if(reqToInsert.size() > 0){
           Database.insert(reqToInsert, false);

        }
        return parentChildRequestsMap;
    }
    
    //Check if parent already exist in the org with the same submition id
    private Request__c checkParentAlreadyExist(String subId){
        List<Request__c> parentReq = [SELECT Id, Submition_Id__c, OwnerId, RecordTypeId, Account__c, Area__c, Business_Name__c, Primary_Contact__c, Program__c, Request_Details__c 
                                		FROM Request__c WHERE Submition_Id__c =: subId AND RecordTypeId =: parentRequest_RT AND createdDate = TODAY];
        if(parentReq.Size() > 0){
            return parentReq[0];
        }
        return null;
    }
    
    //Create parent request
    private Request__c createParent(Request__c childReq){
        Request__c parentReq = new Request__c();
        parentReq.OwnerId = childReq.OwnerId;
        parentReq.RecordTypeId = parentRequest_RT;
        parentReq.Account__c = childReq.Account__c;
        //parentReq.Area__c = childReq.Area__c;
        parentReq.Business_Name__c = childReq.Business_Name__c;
        parentReq.Primary_Contact__c = childReq.Primary_Contact__c;
        parentReq.Program__c = childReq.Program__c;
        parentReq.Request_Details__c = childReq.Request_Details__c;
        parentReq.Submition_Id__c = childReq.Submition_Id__c;
        parentReq.Website_Request__c = childReq.Website_Request__c == true ? true : false;
        return parentReq;
    }

    //Update child => relate them to the parent
    private List<Request__c> updateRelatedChilds(Map<String, Request__c> parentChildRequestsMap, Map<String, List<Request__c>> submitionIdRequestsMap){        
        List<Request__c> requestToUpdate = new List<Request__c>();
        for(String paRq : parentChildRequestsMap.keySet()){                                    
            if(paRq != null && parentChildRequestsMap.get(paRq) != null && submitionIdRequestsMap.get(paRq) != null){
                for(Request__c chRq : submitionIdRequestsMap.get(paRq)){
                    if(chRq != null){
                        Request__c newRqs = new Request__c(Id = chRq.Id);                                                
                        newRqs.Request__c = parentChildRequestsMap.get(paRq).Id;
                        newRqs.Field1__c = true;
                        requestToUpdate.add(newRqs);                        
                    }
                }
            }
        }
        return requestToUpdate;
    }
    
    //Get all child with the same submition id
    private void getSubmitionIdsMap(List<String> submitionIds, Map<String, List<Request__c>> submitionIdRequestsMap, Set<Id> reqIds){
        List<Request__c> relatedRequests = [SELECT Id, Submition_Id__c, OwnerId, RecordTypeId, Account__c, Area__c, Business_Name__c, Primary_Contact__c, Program__c, Request_Details__c 
                                            	FROM Request__c WHERE Submition_Id__c in: submitionIds AND RecordTypeId =: childRequest_RT AND Request__c = null AND Id not in: reqIds];        
        for(Request__c rq : relatedRequests){
            if(submitionIdRequestsMap.containsKey(rq.Submition_Id__c))
            	submitionIdRequestsMap.get(rq.Submition_Id__c).add(rq);
        }
    }
}