force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ארגון</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/contact_from_request__c.field-meta.xml
<CustomField>
    <fullName>contact_from_request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>נא לשייך את איש הקשר מהבקשה לסניף זה</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>סניפים</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>סניף/מקום עבודה</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/Request__c.object-meta.xml
<CustomObject>
    <label>בקשה</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>בקשות</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>District</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Branch__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent_Request</value>
        </filterItems>
        <filterItems>
            <field>Request__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Request__c</referenceTo>
    <relationshipLabel>Requests</relationshipLabel>
    <relationshipName>Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>חדש</label>
            </value>
            <value>
                <fullName>Complete_Info</fullName>
                <label>השלמת פרטים</label>
            </value>
            <value>
                <fullName>Needs_mapping</fullName>
                <label>מיפוי צרכים</label>
            </value>
            <value>
                <fullName>programRequest</fullName>
                <label>המלצה לתכנית</label>
            </value>
            <value>
                <fullName>CloseRequest</fullName>
                <label>סגירת בקשה</label>
            </value>
            <value>
                <fullName>סגור</fullName>
            </value>
            <value>
                <fullName>לא נמצאה תכנית מתאימה</fullName>
                <isActive>false</isActive>
                <label>לא נמצאה תכנית מתאימה</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request__c/fields/Submition_Id__c.field-meta.xml
<CustomField>
    <fullName>Submition_Id__c</fullName>
    <label>Submition Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Request__c/recordTypes/Child_Request.recordType-meta.xml
<RecordType>
    <fullName>Child_Request</fullName>
    <active>true</active>
    <label>בקשה</label>
</RecordType>

force-app/main/default/objects/Request__c/recordTypes/Parent_Request.recordType-meta.xml
<RecordType>
    <fullName>Parent_Request</fullName>
    <active>true</active>
    <label>בקשה מרכזת</label>
</RecordType>

force-app/main/default/globalValueSets/District.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>National</fullName>
        <label>כל הארץ</label>
    </customValue>
    <customValue>
        <fullName>North</fullName>
        <label>צפון</label>
    </customValue>
    <customValue>
        <fullName>Center</fullName>
        <label>מרכז</label>
    </customValue>
    <customValue>
        <fullName>Jerusalem</fullName>
        <label>ירושלים</label>
    </customValue>
    <customValue>
        <fullName>South</fullName>
        <label>דרום</label>
    </customValue>
    <customValue>
        <fullName>Eilat</fullName>
        <label>אילת</label>
    </customValue>
    <masterLabel>District</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RequestHandlerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-06-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   03-17-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
    @IsTest
    public class RequestHandlerTest {
        @isTest
        static void requestTest(){    
            Id parentRequestRTId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Parent_Request').getRecordTypeId();
            Id childRequestRTId = Schema.SObjectType.Request__c.getRecordTypeInfosByDeveloperName().get('Child_Request').getRecordTypeId();
            Id idOfCurrentUser = UserInfo.getUserId();

            Account acc = [SELECT Id FROM Account limit 1];
            Contact con = [SELECT Id FROM Contact limit 1];
            Branch__c br = [SELECT Id FROM Branch__c limit 1];

            List<Request__c> reqList = new List<Request__c>{new Request__c(RecordTypeId = childRequestRTId, Area__c = 'North', Submition_Id__c = '1234', Account__c = acc.Id, Primary_Contact__c = con.Id),
                                                            new Request__c(RecordTypeId = childRequestRTId, Area__c = 'North', Submition_Id__c = '1234', Account__c = acc.Id, Primary_Contact__c = con.Id)};    
            Test.startTest();
            insert reqList;

            reqList[0].Branch__c = br.Id;
            update reqList[0];
            
            Request__c parent = [SELECT Id, RecordTypeId, OwnerId FROM Request__c WHERE RecordTypeId =: parentRequestRTId];
            System.debug('///parent: ' + parent);
            if(parent != null){
                parent.OwnerId = idOfCurrentUser;
                update parent;
            }

            reqList[0].Request_Status__c = 'Complete_Info';
            reqList[1].Request_Status__c = 'Needs_mapping';
            update reqList;

            reqList[0].Request_Status__c = 'Needs_mapping';
            update reqList[0];
            reqList[0].Request_Status__c = 'programRequest';
            update reqList[0];
            reqList[0].Request_Status__c = 'CloseRequest';
            update reqList[0];
            Test.stopTest();
        }
    
        @TestSetup
        static void makeData(){
            Account acc = TEST_Utils.createTestAccount(new List<Account>{new Account()})[0];
            insert acc;

            Contact con = TEST_Utils.createTestContact(new List<Contact>{new Contact(AccountId = acc.Id)})[0];
            insert con;

            List<Branch__c> brList = new List<Branch__c>{new Branch__c(Name = 'Test', Account__c = acc.Id, contact_from_request__c = false, Primary_Contact__c = con.Id),
                                                            new Branch__c(Name = 'Test', Account__c = acc.Id, contact_from_request__c = false, Primary_Contact__c = con.Id)};
            insert brList;
        }

}