force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/contact_from_request__c.field-meta.xml
<CustomField>
    <fullName>contact_from_request__c</fullName>
    <defaultValue>false</defaultValue>
    <label>נא לשייך את איש הקשר מהבקשה לסניף זה</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>איש קשר עיקרי</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>סניפים</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Branch_Handler.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-11-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   05-11-2021   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public with sharing class Branch_Handler extends TriggerHandler{

    public override void beforeInsert(){
        checkConnectionContactToBranch(Trigger.new);
    }

    //Throw error if the user choise two contacts
    private void checkConnectionContactToBranch(List<Branch__c> newBranchs){
        List<Branch__c> branchToConnect = new List<Branch__c>();
        for(Branch__c br : newBranchs){
            if(br.contact_from_request__c == true && br.Primary_Contact__c != null){
                br.addError(Label.AddError_OnlyOneContact);
            }
        }
    }
}