force-app/main/default/objects/Voucher__c/Voucher__c.object-meta.xml
<CustomObject>
    <label>שובר</label>
    <nameField>
        <displayFormat>V-{00000000}</displayFormat>
        <label>מספר שובר</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>שוברים</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher__c/fields/Voucher_Stock__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Stock__c</fullName>
    <label>מלאי</label>
    <referenceTo>Voucher_Stock__c</referenceTo>
    <relationshipLabel>שוברים</relationshipLabel>
    <relationshipName>Vouchers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/dlrs_VoucherTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_VoucherTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_VoucherTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        List<Voucher_Stock__c> vouchStockList = TEST_Utils.createTestVoucherStock(new List<Voucher_Stock__c>{new Voucher_Stock__c()});
        insert vouchStockList;
        
        dlrs.RollupService.testHandler(new Voucher__c(Voucher_Stock__c = vouchStockList[0].Id));
    }
}