force-app/main/default/objects/Voucher_Stock__c/Voucher_Stock__c.object-meta.xml
<CustomObject>
    <label>מלאי</label>
    <nameField>
        <label>סוג מלאי</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>מלאי</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voucher_Stock__c/fields/Qty_vouchers_available__c.field-meta.xml
<CustomField>
    <fullName>Qty_vouchers_available__c</fullName>
    <formula>Initial_amount_vouchers__c  -  Qty_vouchers_requested__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>כמות שוברים זמינה</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/VoucherStockHandler.cls
public with sharing class VoucherStockHandler extends TriggerHandler{
    
    public override void beforeUpdate(){
        beforeUpdateGetSuitableRecord(Trigger.new, Trigger.oldMap);
    }

    //-----------------------------Before Update--------------------------------
    private void beforeUpdateGetSuitableRecord(List<Voucher_Stock__c> newRequest, Map<Id, SObject> oldMapRequest){
        for(Voucher_Stock__c vs : newRequest){
            Voucher_Stock__c oldProRequest = (Voucher_Stock__c)oldMapRequest.get(vs.Id);
            if(vs.Qty_vouchers_available__c != oldProRequest.Qty_vouchers_available__c){
                if(vs.Qty_vouchers_available__c > 0 && oldProRequest.Qty_vouchers_available__c == 0){
                    vs.Send_Email__c = true;
                } else if(vs.Qty_vouchers_available__c == 0 && oldProRequest.Qty_vouchers_available__c > 0){
                    vs.Send_Email__c = false;
                }
            }
        }
    }
    
}